import './analytics-coverage-init.test.initialization'
import './analytics-coverage-init.test.interaction'
import './analytics-coverage-init.test.gtag'
import './analytics-coverage-init.test.umami'
import './analytics-coverage-init.test.send-to-umami'
import './analytics-coverage-init.test.gating'
