import { describe, it, expect } from 'vitest'
import {
  STORAGE_KEY_TOKEN,
  STORAGE_KEY_AUTH_TOKEN,
  STORAGE_KEY_GITHUB_TOKEN,
  STORAGE_KEY_GITHUB_TOKEN_SOURCE,
  STORAGE_KEY_GITHUB_TOKEN_DISMISSED,
  STORAGE_KEY_FEEDBACK_GITHUB_TOKEN,
  STORAGE_KEY_HAS_FEEDBACK_GITHUB_TOKEN,
  STORAGE_KEY_FEEDBACK_GITHUB_TOKEN_SOURCE,
  STORAGE_KEY_FEEDBACK_GITHUB_TOKEN_DISMISSED,
  DEMO_TOKEN_VALUE,
  STORAGE_KEY_DEMO_MODE,
  STORAGE_KEY_ONBOARDED,
  STORAGE_KEY_ONBOARDING_RESPONSES,
  STORAGE_KEY_USER_CACHE,
  STORAGE_KEY_HAS_SESSION,
  STORAGE_KEY_SQLITE_MIGRATED,
  STORAGE_KEY_AI_MODE,
  STORAGE_KEY_PREDICTION_SETTINGS,
  STORAGE_KEY_TOKEN_SETTINGS,
  STORAGE_KEY_THEME,
  STORAGE_KEY_CUSTOM_THEMES,
  STORAGE_KEY_ACCESSIBILITY,
  STORAGE_KEY_NOTIFICATION_CONFIG,
  STORAGE_KEY_TOUR_COMPLETED,
  STORAGE_KEY_PENDING_SETTINGS_SYNC,
  STORAGE_KEY_ANALYTICS_OPT_OUT,
  STORAGE_KEY_ANONYMOUS_USER_ID,
  STORAGE_KEY_MAIN_DASHBOARD_CARDS,
  STORAGE_KEY_DASHBOARD_AUTO_REFRESH,
  STORAGE_KEY_CLUSTER_LAYOUT,
  STORAGE_KEY_NAV_HISTORY,
  STORAGE_KEY_CLUSTER_PROVIDER_OVERRIDES,
  STORAGE_KEY_CLUSTER_ORDER,
  STORAGE_KEY_MISSIONS_ACTIVE,
  STORAGE_KEY_MISSIONS_HISTORY,
  STORAGE_KEY_NUDGE_DISMISSED,
  STORAGE_KEY_SMART_SUGGESTIONS_DISMISSED,
  STORAGE_KEY_DRAG_HINT_SHOWN,
  STORAGE_KEY_PWA_PROMPT_DISMISSED,
  STORAGE_KEY_SESSION_COUNT,
  STORAGE_KEY_VISIT_COUNT,
  STORAGE_KEY_FEATURE_HINTS_DISMISSED,
  STORAGE_KEY_GETTING_STARTED_DISMISSED,
  STORAGE_KEY_HINTS_SUPPRESSED,
  STORAGE_KEY_POST_CONNECT_DISMISSED,
  STORAGE_KEY_DEMO_CTA_DISMISSED,
  STORAGE_KEY_ADOPTER_NUDGE_DISMISSED,
  STORAGE_KEY_FIRST_AGENT_CONNECT,
  STORAGE_KEY_VISIT_STREAK,
  STORAGE_KEY_SEEN_TIPS,
  STORAGE_KEY_NPS_STATE,
  STORAGE_KEY_GROUND_CONTROL_DASHBOARDS,
  STORAGE_KEY_SNOOZED_CARDS,
  STORAGE_KEY_SNOOZED_RECOMMENDATIONS,
  STORAGE_KEY_NOTIFIED_ALERT_KEYS,
  STORAGE_KEY_OPA_CACHE,
  STORAGE_KEY_OPA_CACHE_TIME,
  STORAGE_KEY_KYVERNO_CACHE,
  STORAGE_KEY_KYVERNO_CACHE_TIME,
  STORAGE_KEY_KUBESCAPE_CACHE,
  STORAGE_KEY_KUBESCAPE_CACHE_TIME,
  STORAGE_KEY_TRIVY_CACHE,
  STORAGE_KEY_TRIVY_CACHE_TIME,
  STORAGE_KEY_TRESTLE_CACHE,
  STORAGE_KEY_TRESTLE_CACHE_TIME,
  STORAGE_KEY_KUBECTL_HISTORY,
  STORAGE_KEY_RBAC_CACHE,
  STORAGE_KEY_RBAC_CACHE_TIME,
  STORAGE_KEY_INTOTO_CACHE,
  STORAGE_KEY_INTOTO_CACHE_TIME,
  STORAGE_KEY_NS_OVERVIEW_CLUSTER,
  STORAGE_KEY_NS_OVERVIEW_NAMESPACE,
  STORAGE_KEY_DRASI_CONNECTIONS,
  STORAGE_KEY_DRASI_ACTIVE_CONNECTION,
  STORAGE_KEY_AUTONOMOUS_BANNER_DISMISSED,
  STORAGE_KEY_STELLAR_ATTENTION_DISMISSED,
  STORAGE_KEY_STELLAR_BATCH_INTERVAL_MS,
} from '../storage'

const storageConstants = {
  STORAGE_KEY_TOKEN,
  STORAGE_KEY_AUTH_TOKEN,
  STORAGE_KEY_GITHUB_TOKEN,
  STORAGE_KEY_GITHUB_TOKEN_SOURCE,
  STORAGE_KEY_GITHUB_TOKEN_DISMISSED,
  STORAGE_KEY_FEEDBACK_GITHUB_TOKEN,
  STORAGE_KEY_HAS_FEEDBACK_GITHUB_TOKEN,
  STORAGE_KEY_FEEDBACK_GITHUB_TOKEN_SOURCE,
  STORAGE_KEY_FEEDBACK_GITHUB_TOKEN_DISMISSED,
  DEMO_TOKEN_VALUE,
  STORAGE_KEY_DEMO_MODE,
  STORAGE_KEY_ONBOARDED,
  STORAGE_KEY_ONBOARDING_RESPONSES,
  STORAGE_KEY_USER_CACHE,
  STORAGE_KEY_HAS_SESSION,
  STORAGE_KEY_SQLITE_MIGRATED,
  STORAGE_KEY_AI_MODE,
  STORAGE_KEY_PREDICTION_SETTINGS,
  STORAGE_KEY_TOKEN_SETTINGS,
  STORAGE_KEY_THEME,
  STORAGE_KEY_CUSTOM_THEMES,
  STORAGE_KEY_ACCESSIBILITY,
  STORAGE_KEY_NOTIFICATION_CONFIG,
  STORAGE_KEY_TOUR_COMPLETED,
  STORAGE_KEY_PENDING_SETTINGS_SYNC,
  STORAGE_KEY_ANALYTICS_OPT_OUT,
  STORAGE_KEY_ANONYMOUS_USER_ID,
  STORAGE_KEY_MAIN_DASHBOARD_CARDS,
  STORAGE_KEY_DASHBOARD_AUTO_REFRESH,
  STORAGE_KEY_CLUSTER_LAYOUT,
  STORAGE_KEY_NAV_HISTORY,
  STORAGE_KEY_CLUSTER_PROVIDER_OVERRIDES,
  STORAGE_KEY_CLUSTER_ORDER,
  STORAGE_KEY_MISSIONS_ACTIVE,
  STORAGE_KEY_MISSIONS_HISTORY,
  STORAGE_KEY_NUDGE_DISMISSED,
  STORAGE_KEY_SMART_SUGGESTIONS_DISMISSED,
  STORAGE_KEY_DRAG_HINT_SHOWN,
  STORAGE_KEY_PWA_PROMPT_DISMISSED,
  STORAGE_KEY_SESSION_COUNT,
  STORAGE_KEY_VISIT_COUNT,
  STORAGE_KEY_FEATURE_HINTS_DISMISSED,
  STORAGE_KEY_GETTING_STARTED_DISMISSED,
  STORAGE_KEY_HINTS_SUPPRESSED,
  STORAGE_KEY_POST_CONNECT_DISMISSED,
  STORAGE_KEY_DEMO_CTA_DISMISSED,
  STORAGE_KEY_ADOPTER_NUDGE_DISMISSED,
  STORAGE_KEY_FIRST_AGENT_CONNECT,
  STORAGE_KEY_VISIT_STREAK,
  STORAGE_KEY_SEEN_TIPS,
  STORAGE_KEY_NPS_STATE,
  STORAGE_KEY_GROUND_CONTROL_DASHBOARDS,
  STORAGE_KEY_SNOOZED_CARDS,
  STORAGE_KEY_SNOOZED_RECOMMENDATIONS,
  STORAGE_KEY_NOTIFIED_ALERT_KEYS,
  STORAGE_KEY_OPA_CACHE,
  STORAGE_KEY_OPA_CACHE_TIME,
  STORAGE_KEY_KYVERNO_CACHE,
  STORAGE_KEY_KYVERNO_CACHE_TIME,
  STORAGE_KEY_KUBESCAPE_CACHE,
  STORAGE_KEY_KUBESCAPE_CACHE_TIME,
  STORAGE_KEY_TRIVY_CACHE,
  STORAGE_KEY_TRIVY_CACHE_TIME,
  STORAGE_KEY_TRESTLE_CACHE,
  STORAGE_KEY_TRESTLE_CACHE_TIME,
  STORAGE_KEY_KUBECTL_HISTORY,
  STORAGE_KEY_RBAC_CACHE,
  STORAGE_KEY_RBAC_CACHE_TIME,
  STORAGE_KEY_INTOTO_CACHE,
  STORAGE_KEY_INTOTO_CACHE_TIME,
  STORAGE_KEY_NS_OVERVIEW_CLUSTER,
  STORAGE_KEY_NS_OVERVIEW_NAMESPACE,
  STORAGE_KEY_DRASI_CONNECTIONS,
  STORAGE_KEY_DRASI_ACTIVE_CONNECTION,
  STORAGE_KEY_AUTONOMOUS_BANNER_DISMISSED,
  STORAGE_KEY_STELLAR_ATTENTION_DISMISSED,
  STORAGE_KEY_STELLAR_BATCH_INTERVAL_MS,
}

describe('storage constants', () => {
  it('exports all expected auth keys', () => {
    expect(storageConstants.STORAGE_KEY_TOKEN).toBe('token')
    expect(storageConstants.DEMO_TOKEN_VALUE).toBe('demo-token')
    expect(storageConstants.STORAGE_KEY_FEEDBACK_GITHUB_TOKEN).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_HAS_FEEDBACK_GITHUB_TOKEN).toBeTruthy()
  })

  it('exports demo/onboarding keys', () => {
    expect(storageConstants.STORAGE_KEY_DEMO_MODE).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_ONBOARDED).toBeTruthy()
  })

  it('exports settings keys', () => {
    expect(storageConstants.STORAGE_KEY_AI_MODE).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_THEME).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_ACCESSIBILITY).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_TOUR_COMPLETED).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_ANALYTICS_OPT_OUT).toBeTruthy()
  })

  it('exports engagement keys', () => {
    expect(storageConstants.STORAGE_KEY_NUDGE_DISMISSED).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_SESSION_COUNT).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_VISIT_COUNT).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_VISIT_STREAK).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_SEEN_TIPS).toBeTruthy()
  })

  it('exports cache keys', () => {
    expect(storageConstants.STORAGE_KEY_OPA_CACHE).toBeTruthy()
    expect(storageConstants.STORAGE_KEY_KYVERNO_CACHE).toBeTruthy()
  })

  it('all values are strings', () => {
    for (const [, value] of Object.entries(storageConstants)) {
      expect(typeof value).toBe('string')
    }
  })

  it('no duplicate values', () => {
    const values = Object.values(storageConstants)
    const unique = new Set(values)
    expect(unique.size).toBe(values.length)
  })
})
