import type { MissionControlState } from './types'
import { generateDefaultPhases } from './BlueprintInfoPanels'
import { shortenClusterName } from './BlueprintReport'

export function buildApprovalIssueBody(
  state: MissionControlState,
  installedProjects: Set<string>,
  notes?: string,
  reviewUrl?: string,
): string {
  const effectivePhases = state.phases.length > 0
    ? state.phases
    : generateDefaultPhases(state.projects)

  const projectRows = state.projects.map(p => {
    const status = installedProjects.has(p.name) ? 'Installed' : 'Needs Deploy'
    return `| ${p.displayName} | ${p.category} | ${p.priority} | ${status} | ${p.reason || '—'} |`
  }).join('\n')

  const clusterRows = state.assignments
    .filter(a => (a.projectNames ?? []).length > 0)
    .map(a => {
      const projs = (a.projectNames ?? []).map(n =>
        installedProjects.has(n) ? `${n} ✅` : n
      ).join(', ')
      return `| ${shortenClusterName(a.clusterName)} | ${(a.projectNames ?? []).length} | ${projs} |`
    }).join('\n')

  const phaseRows = effectivePhases.map(phase => {
    const projs = phase.projectNames.map(n =>
      installedProjects.has(n) ? `${n} ✅` : n
    ).join(', ')
    const est = phase.estimatedSeconds
      ? `${Math.ceil(phase.estimatedSeconds / 60)} min`
      : '—'
    return `| ${phase.phase}. ${phase.name} | ${est} | ${projs} |`
  }).join('\n')

  const totalEstMin = effectivePhases.reduce((sum, p) => sum + (p.estimatedSeconds ?? 0), 0)
  const totalEstStr = totalEstMin > 0 ? `${Math.ceil(totalEstMin / 60)} min estimated` : ''

  const notesSection = notes
    ? `\n---\n\n### Notes from Requester\n\n${notes}\n`
    : ''

  const reviewLinkSection = reviewUrl
    ? `\n> 🔗 **[View this plan interactively in KubeStellar Console](${reviewUrl})**\n`
    : ''

  return `## Mission Control — Deployment Approval Request

> **This deployment plan was generated by [KubeStellar Console](https://console.kubestellar.io) Mission Control and requires approval before proceeding.**
${reviewLinkSection}
### Mission

${state.description || '_No description provided_'}
${notesSection}
---

### Projects (${state.projects.length})

| Project | Category | Priority | Status | Reason |
|---------|----------|----------|--------|--------|
${projectRows}

---

### Cluster Assignments (${state.assignments.filter(a => (a.projectNames ?? []).length > 0).length} clusters)

| Cluster | Projects | Assignments |
|---------|----------|-------------|
${clusterRows}

---

### Phased Rollout Plan (${effectivePhases.length} phases${totalEstStr ? ` · ${totalEstStr}` : ''})

| Phase | Estimate | Projects |
|-------|----------|----------|
${phaseRows}

---

### Approval Checklist

- [ ] Reviewed project selections and priorities
- [ ] Verified cluster assignments and readiness
- [ ] Confirmed phased rollout order and dependencies
- [ ] Approved for deployment

---

<sub>Generated by KubeStellar Console Mission Control · ${new Date().toISOString().split('T')[0]}</sub>
`
}
