/**
 * Übersicht card widget generator.
 */

import { WIDGET_CARDS } from '../widgetRegistry'
import { generateWidgetStyles, generateWidgetShell } from '../styleConverter'
import { resolveWidgetEndpoint, generateWidgetCommand } from '../codeGenerator.utils'
import { generateCardRenderFunction } from './cardRenderers'

export function generateCardWidget(
  cardType: string,
  apiEndpoint: string,
  refreshInterval: number = 30000,
): string {
  const card = WIDGET_CARDS[cardType]
  if (!card) {
    throw new Error(`Unknown card type: ${cardType}`)
  }

  const baseUrl = resolveWidgetEndpoint(apiEndpoint, card.apiEndpoints[0])
  /** Append source param so the backend can attribute traffic from exported widgets */
  const curlUrl = baseUrl + (baseUrl.includes('?') ? '&' : '?') + 'source=ubersicht-widget'
  const widgetName = cardType.replace(/_/g, '-')
  const consoleUrl = (apiEndpoint || 'http://localhost:8080').replace(/\/api$/, '')
  const shellCode = generateWidgetShell(widgetName, consoleUrl)

  return `/**
 * ${card.displayName} Widget
 * ${card.description}
 *
 * Generated by KubeStellar Console
 * Install: Move to ~/Library/Application Support/Übersicht/widgets/
 * Drag the ⋮⋮ handle to reposition. Position is saved automatically.
 */

${shellCode}

// Fetch agent token for auth, then fetch data (Übersicht's WebKit does not support fetch)
export const command = \`${generateWidgetCommand(consoleUrl, curlUrl)}\`;

export const refreshFrequency = ${refreshInterval};

${generateWidgetStyles()}

${generateCardRenderFunction(cardType, card.displayName)}
`
}
