/**
 * Übersicht stat widget generators.
 */

import { WIDGET_STATS } from '../widgetRegistry'
import { generateWidgetStyles } from '../styleConverter'
import { generateWidgetCommand } from '../codeGenerator.utils'

// Generate Übersicht widget code for stat blocks
export function generateStatWidget(
  statIds: string[],
  apiEndpoint: string,
  refreshInterval: number = 60000,
  layout: 'row' | 'grid' = 'row'
): string {
  const stats = statIds.map((id) => WIDGET_STATS[id]).filter(Boolean)
  if (stats.length === 0) {
    throw new Error('No valid stat IDs provided')
  }

  const base = apiEndpoint || 'http://localhost:8081'
  const endpoint = `${base}${stats[0].apiEndpoint}`
  const curlUrl = endpoint + (endpoint.includes('?') ? '&' : '?') + 'source=ubersicht-widget'

  return `/**
 * Stats Widget
 * Displays: ${stats.map((s) => s.displayName).join(', ')}
 *
 * Generated by KubeStellar Console
 */

// Fetch agent token for auth, then fetch data (Übersicht's WebKit does not support fetch)
export const command = \`${generateWidgetCommand(base, curlUrl)}\`;

export const refreshFrequency = ${refreshInterval};

${generateWidgetStyles()}

const WIDGET_NAME = 'stats-widget';
const openIssue = (errorMsg) => {
  const title = encodeURIComponent('[Widget] ' + WIDGET_NAME + ': ' + (errorMsg || 'unknown error'));
  const body = encodeURIComponent('**Widget:** ' + WIDGET_NAME + '\\n**Error:** ' + (errorMsg || 'unknown') + '\\n**Platform:** Übersicht (macOS)\\n\\n_Describe what you were doing when this happened:_\\n');
  run(\`open "https://github.com/kubestellar/console/issues/new?title=\${title}&body=\${body}&labels=kind/bug,area/widgets"\`);
};

const StatBlock = ({ value, label, color }) => (
  <div style={{...styles.statBlock, borderTop: \`3px solid \${color}\`}}>
    <span style={{...styles.statValue, color}}>{value}</span>
    <span style={styles.statLabel}>{label}</span>
  </div>
);

export const render = ({ output }) => {
  let data = null;
  let error = null;
  try {
    const trimmed = (output || '').trim();
    if (!trimmed || trimmed.includes('"error"')) {
      error = 'Load failed';
    } else {
      data = JSON.parse(trimmed);
    }
  } catch (e) {
    error = 'Parse error';
  }

  if (error) {
    return <div style={{...styles.column}}><div style={styles.row}><span style={{color: styles.colors.error}}>Error</span></div><div><button style={styles.issueBtn} onClick={() => openIssue(error)}>Report Issue</button></div></div>;
  }

  // Extract values from API responses.
  // Supports dotted paths ('a.b.c') AND bracket notation for array/numeric
  // index access ('items[0].foo.bar'). Without the bracket handling, a path
  // like 'items[0]' would be walked as src['items[0]'] which is always
  // undefined and silently returns 0, making stat widgets look broken.
  const getData = (path, src) => {
    try {
      const tokens = String(path)
        .replace(/\\[(\\w+)\\]/g, '.$1')
        .split('.')
        .filter(Boolean);
      let cur = src;
      for (const t of tokens) {
        if (cur == null) return 0;
        cur = cur[t];
      }
      return cur ?? 0;
    } catch {
      return 0;
    }
  };

  return (
    <div style={{...styles.${layout}, ${layout === 'grid' ? "gridTemplateColumns: 'repeat(2, 1fr)'" : ''}}}>
      ${stats
        .map((stat) => {
          return `<StatBlock
        value={getData('${stat.dataPath}', data)}
        label="${stat.displayName}"
        color="${stat.color}"
      />`
        })
        .join('\n      ')}
    </div>
  );
};
`
}
