/**
 * Übersicht template widget generators.
 */

import { WIDGET_CARDS, WIDGET_STATS, WIDGET_TEMPLATES } from '../widgetRegistry'
import { generateWidgetStyles } from '../styleConverter'
import { generateWidgetCommand } from '../codeGenerator.utils'
import { generateMiniStatComponent } from './stats'

// Generate Übersicht widget code for a template
export function generateTemplateWidget(
  templateId: string,
  apiEndpoint: string,
  refreshInterval: number = 30000
): string {
  const template = WIDGET_TEMPLATES[templateId]
  if (!template) {
    throw new Error(`Unknown template ID: ${templateId}`)
  }

  // Collect all API endpoints from cards and stats
  const allEndpoints: string[] = []
  template.cards.forEach((cardType) => {
    const card = WIDGET_CARDS[cardType]
    if (card) {
      card.apiEndpoints.forEach((ep) => {
        if (!allEndpoints.includes(ep)) allEndpoints.push(ep)
      })
    }
  })
  template.stats?.forEach((statId) => {
    const stat = WIDGET_STATS[statId]
    if (stat && !allEndpoints.includes(stat.apiEndpoint)) allEndpoints.push(stat.apiEndpoint)
  })
  const validEndpoints = allEndpoints.filter((ep): ep is string => typeof ep === 'string' && ep.length > 0)
  const firstEndpoint = validEndpoints[0]
  if (!firstEndpoint) {
    throw new Error(`Template "${templateId}" has no resolvable data endpoint (no cards and no stat.apiEndpoint)`)
  }
  const base = apiEndpoint || 'http://localhost:8081'
  const curlUrl = `${base}${firstEndpoint}`

  const statComponents = (template.stats || []).map((id: string) => generateMiniStatComponent(id)).join('\n\n')

  return `/**
 * ${template.displayName} Template Widget
 * ${template.description}
 *
 * Generated by KubeStellar Console
 */

// Fetch agent token for auth, then fetch data (Übersicht's WebKit does not support fetch)
export const command = \`${generateWidgetCommand(base, curlUrl)}\`;

export const refreshFrequency = ${refreshInterval};

${generateWidgetStyles()}

const WIDGET_NAME = '${templateId.replace(/_/g, '-')}';
const openIssue = (errorMsg) => {
  const title = encodeURIComponent('[Widget] ' + WIDGET_NAME + ': ' + (errorMsg || 'unknown error'));
  const body = encodeURIComponent('**Widget:** ' + WIDGET_NAME + '\\n**Error:** ' + (errorMsg || 'unknown') + '\\n**Platform:** Übersicht (macOS)\\n\\n_Describe what you were doing when this happened:_\\n');
  run(\`open "https://github.com/kubestellar/console/issues/new?title=\${title}&body=\${body}&labels=kind/bug,area/widgets"\`);
};

${statComponents}

export const render = ({ output }) => {
  let data = null;
  let error = null;
  try {
    const trimmed = (output || '').trim();
    if (!trimmed || trimmed.includes('"error"')) {
      error = 'Load failed';
    } else {
      data = JSON.parse(trimmed);
    }
  } catch (e) {
    error = 'Parse error';
  }

  if (error) {
    return (
      <div style={styles.column}>
        <div style={styles.row}>
          <span style={{color: styles.colors.error}}>Error</span>
        </div>
        <div>
          <button style={styles.issueBtn} onClick={() => openIssue(error)}>
            Report Issue
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={styles.column}>
      <h3 style={{margin: '0 0 12px 0', fontSize: '16px'}}>${template.displayName}</h3>
      ${
        template.stats && template.stats.length > 0
          ? `<div style={styles.row}>
        ${template.stats.map((id: string) => `<${id.replace(/_/g, '')}Stat data={data} />`).join('\n        ')}
      </div>`
          : ''
      }
    </div>
  );
};
`
}

// Generate mini stat component for templates
export function generateMiniStatComponent(statId: string): string {
  const stat = WIDGET_STATS[statId]
  if (!stat) return ''

  const componentName = statId.replace(/_/g, '') + 'Stat'

  return `const ${componentName} = ({ data }) => {
  const value = (() => {
    try {
      return ${stat.dataPath.includes('reduce') || stat.dataPath.includes('filter') ? `(data?.${stat.dataPath.split('.')[0]} || []).${stat.dataPath.split('.').slice(1).join('.')}` : `data?.${stat.dataPath}`} || 0;
    } catch { return 0; }
  })();
  return (
    <div style={{...styles.statBlock, borderTop: '2px solid ${stat.color}'}}>
      <span style={{...styles.statValue, fontSize: '18px', color: '${stat.color}'}}>{value}${stat.format === 'percentage' ? '%' : ''}</span>
      <span style={{...styles.statLabel, fontSize: '9px'}}>${stat.displayName}</span>
    </div>
  );
};`
}
