import type { KnownRoute } from './RouteSearchPanel'

const ROUTE_ICONS: Record<string, string> = {
  '/': 'LayoutDashboard',
  '/clusters': 'Server',
  '/workloads': 'Box',
  '/compute': 'Cpu',
  '/events': 'Activity',
  '/security': 'Shield',
  '/gitops': 'GitBranch',
  '/alerts': 'Bell',
  '/cost': 'DollarSign',
  '/security-posture': 'ShieldCheck',
  '/data-compliance': 'Database',
  '/gpu-reservations': 'Zap',
  '/storage': 'HardDrive',
  '/network': 'Network',
  '/arcade': 'Gamepad2',
  '/deploy': 'Rocket',
  '/ai-ml': 'Brain',
  '/ci-cd': 'GitPullRequest',
  '/ai-agents': 'Bot',
  '/llm-d-benchmarks': 'TrendingUp',
  '/compliance': 'ClipboardCheck',
  '/enterprise': 'Building2',
  '/enterprise/frameworks': 'ClipboardCheck',
  '/enterprise/change-control': 'GitPullRequest',
  '/enterprise/sod': 'Users',
  '/enterprise/data-residency': 'Globe',
  '/enterprise/reports': 'FileText',
  '/enterprise/hipaa': 'Heart',
  '/enterprise/gxp': 'FlaskConical',
  '/enterprise/baa': 'Handshake',
  '/enterprise/nist': 'Shield',
  '/enterprise/stig': 'ShieldCheck',
  '/enterprise/air-gap': 'WifiOff',
  '/enterprise/fedramp': 'Landmark',
  '/enterprise/oidc': 'KeyRound',
  '/enterprise/rbac-audit': 'UserCheck',
  '/enterprise/sessions': 'Clock',
  '/enterprise/siem': 'Radar',
  '/enterprise/incident-response': 'AlertTriangle',
  '/enterprise/threat-intel': 'Eye',
  '/enterprise/sbom': 'Package',
  '/enterprise/sigstore': 'Lock',
  '/enterprise/slsa': 'Container',
  '/enterprise/risk-matrix': 'Grid3x3',
  '/enterprise/risk-register': 'ClipboardList',
  '/enterprise/risk-appetite': 'Scale',
  '/karmada-ops': 'Globe',
  '/cluster-admin': 'ShieldAlert',
  '/multi-tenancy': 'Users',
  '/drasi': 'GitBranch',
  '/namespaces': 'FolderTree',
  '/nodes': 'HardDrive',
  '/pods': 'Package',
  '/deployments': 'Rocket',
  '/services': 'Network',
  '/operators': 'Cog',
  '/helm': 'Ship',
  '/logs': 'FileText',
  '/settings': 'Settings',
  '/users': 'Users',
}

export function buildKnownRoutes(t: (key: string) => string): KnownRoute[] {
  return Object.entries(ROUTE_ICONS).map(([href, icon]) => {
    const key = `sidebar.routes.${href}`

    return {
      href,
      name: t(`${key}.name`),
      description: t(`${key}.description`),
      icon,
      category: t(`${key}.category`),
    }
  })
}
