import type { Source, Criterion, LevelDef } from './types'

const LEVELS: LevelDef[] = [
  {
    n: 1,
    name: 'Assisted',
    role: 'Executor',
    characteristic: 'Humans write code with AI suggesting completions. No persistent instructions, no measurement, no feedback loops beyond the IDE session itself.',
    transitionTrigger: '"I keep repeating the same corrections to the AI."',
    antiPattern: 'Tool-chasing: adopting every new model or IDE plugin in search of productivity that only comes from encoding judgment.',
  },
  {
    n: 2,
    name: 'Instructed',
    role: 'Rule-writer',
    characteristic: 'The team encodes rules, style, and forbidden patterns into instruction files that the AI reads at the start of every session. Judgment is now written down, not remembered.',
    transitionTrigger: '"I want measurement."',
    antiPattern: 'Instruction rot: letting CLAUDE.md drift out of sync with the code so the rules stop matching reality.',
  },
  {
    n: 3,
    name: 'Measured',
    role: 'Analyst',
    characteristic: 'The team instruments the AI loop itself: PR acceptance rate, coverage deltas, review-comment density, time-to-merge. Metrics surface which instructions actually work.',
    transitionTrigger: '"I want the system to tune itself from the metrics."',
    antiPattern: 'Dashboard graveyard: building measurement no one acts on. A metric that does not change a workflow is overhead, not maturity.',
  },
  {
    n: 4,
    name: 'Adaptive',
    role: 'Governor',
    characteristic: 'The loop closes: metrics feed back into instructions, review rules, and gating thresholds automatically. Humans set policy; the system tunes itself to meet it.',
    transitionTrigger: '"I want the system to decide what work to do next."',
    antiPattern: 'Policy theater: auto-tuning thresholds without a human-readable explanation of why they changed.',
  },
  {
    n: 5,
    name: 'Self-Sustaining',
    role: 'Strategist',
    characteristic: 'The codebase proposes its own work, triages its own issues, and gates its own merges. Humans hold 15-20% of contributions — the share that requires strategic judgment, not execution.',
    transitionTrigger: 'None — L5 is the terminal state. The human role becomes direction-setting, not code writing.',
    antiPattern: 'Mistaking autonomy for abandonment: a self-sustaining codebase still needs a strategist to set direction, or it drifts toward local optima.',
  },
]

const CRITERIA: Criterion[] = [
  // L2 — Instructed: instruction files and prompt conventions
  {
    id: 'acmm:claude-md',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'CLAUDE.md instructions',
    description: 'Project-level instructions loaded by Claude Code at every session start.',
    rationale: 'The foundational L2 feedback loop: encoding judgment as text the AI reads every session.',
    detection: { type: 'path', pattern: 'CLAUDE.md' },
    referencePath: 'CLAUDE.md',
    frequency: 'Every AI session',
  },
  {
    id: 'acmm:copilot-instructions',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'Copilot instructions',
    description: 'GitHub Copilot repository instructions loaded on every Copilot interaction.',
    rationale: 'Same L2 signal as CLAUDE.md, scoped to Copilot users.',
    detection: { type: 'path', pattern: '.github/copilot-instructions.md' },
    referencePath: '.github/copilot-instructions.md',
    frequency: 'Every Copilot session',
  },
  {
    id: 'acmm:agents-md',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'AGENTS.md shared directives',
    description: 'Cross-tool agent instructions readable by any AI coding tool.',
    rationale: 'Portable instructions that survive tool changes — an L2 durability signal.',
    detection: { type: 'path', pattern: 'AGENTS.md' },
    frequency: 'Every AI session',
  },
  {
    id: 'acmm:cursor-rules',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'Cursor rules',
    description: 'Cursor IDE project rules that guide its agent.',
    rationale: 'Tool-specific L2 signal for Cursor users.',
    detection: { type: 'any-of', pattern: ['.cursor/rules', '.cursorrules'] },
    frequency: 'Every Cursor session',
  },
  {
    id: 'acmm:prompts-catalog',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'Prompt catalog',
    description: 'Committed prompt templates for recurring tasks.',
    rationale: 'Reusing prompts across the team turns tribal knowledge into shared L2 assets.',
    detection: { type: 'any-of', pattern: ['prompts/', '.prompts/', 'docs/prompts/', '.github/prompts/', '.github/agents/'] },
  },
  {
    id: 'acmm:pr-template',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'Pull request template',
    description: 'Structured PR description template that guides both humans and AI.',
    rationale: 'A template nudges every PR through the same reasoning — an L2 structural aid.',
    detection: { type: 'any-of', pattern: ['.github/pull_request_template.md', '.github/PULL_REQUEST_TEMPLATE.md'] },
    referencePath: '.github/pull_request_template.md',
  },
  {
    id: 'acmm:issue-template',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'Issue template',
    description: 'Structured issue form that ensures every report is triageable by the AI.',
    rationale: 'L2 governance aid — forces consistent issue shape so automation can classify.',
    detection: { type: 'any-of', pattern: ['.github/ISSUE_TEMPLATE/', '.github/issue_template.md'] },
  },
  {
    id: 'acmm:contrib-guide',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'Contributing guide',
    description: 'CONTRIBUTING.md used both by humans and AI to understand contribution rules.',
    rationale: 'Documented process is an L2 signal the team has articulated how work enters the repo.',
    detection: { type: 'any-of', pattern: ['CONTRIBUTING.md', '.github/CONTRIBUTING.md'] },
  },
  {
    id: 'acmm:style-config',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'Code style config',
    description: 'Committed formatter/linter config (eslint, prettier, gofmt, ruff, etc.).',
    rationale: 'Style rules expressed as config — L2 mechanized judgment.',
    detection: { type: 'any-of', pattern: ['.eslintrc', '.eslintrc.json', '.eslintrc.js', 'eslint.config.js', '.prettierrc', 'ruff.toml', '.golangci.yml'] },
  },
  {
    id: 'acmm:editor-config',
    source: 'acmm',
    level: 2,
    category: 'feedback-loop',
    name: 'EditorConfig',
    description: '.editorconfig for cross-editor consistency.',
    rationale: 'Baseline L2 consistency signal — trivial to add, hard to retrofit.',
    detection: { type: 'path', pattern: '.editorconfig' },
  },

  // L3 — Measured: the metrics that tell you the loop is working
  {
    id: 'acmm:coverage-gate',
    source: 'acmm',
    level: 3,
    category: 'feedback-loop',
    name: 'Coverage gate workflow',
    description: 'CI workflow that fails PRs below a coverage threshold.',
    rationale: 'L3 measurement: the first metric you encode as a blocking signal.',
    detection: { type: 'any-of', pattern: ['.github/workflows/coverage-gate.yml', '.github/workflows/coverage.yml'] },
    referencePath: '.github/workflows/coverage-gate.yml',
  },
  {
    id: 'acmm:pr-acceptance-metric',
    source: 'acmm',
    level: 3,
    category: 'feedback-loop',
    name: 'PR acceptance tracking',
    description: 'Scheduled job that tracks AI PR acceptance rate over time.',
    rationale: 'L3 meta-metric: measuring the feedback loop itself, not just the code.',
    detection: { type: 'any-of', pattern: ['scripts/build-accm-history.mjs', '.github/workflows/accm-history-update.yml', 'scripts/pr-metrics.mjs'] },
    referencePath: 'scripts/build-accm-history.mjs',
  },
  {
    id: 'acmm:test-suite',
    source: 'acmm',
    level: 3,
    category: 'feedback-loop',
    name: 'Automated test suite',
    description: 'A test runner config and at least one test directory.',
    rationale: 'L3 precondition: you cannot measure what is not tested.',
    detection: { type: 'any-of', pattern: ['vitest.config.ts', 'vitest.config.js', 'jest.config.js', 'jest.config.ts', 'go.mod', 'pytest.ini', 'pyproject.toml'] },
  },
  {
    id: 'acmm:e2e-tests',
    source: 'acmm',
    level: 3,
    category: 'feedback-loop',
    name: 'End-to-end tests',
    description: 'Playwright, Cypress, or equivalent e2e test suite.',
    rationale: 'L3 user-path measurement — unit tests alone do not tell you the feature works.',
    detection: { type: 'any-of', pattern: ['playwright.config.ts', 'playwright.config.js', 'cypress.config.ts', 'cypress.config.js', 'e2e/', 'tests/e2e/'] },
  },
  {
    id: 'acmm:pr-review-rubric',
    source: 'acmm',
    level: 3,
    category: 'feedback-loop',
    name: 'PR review rubric',
    description: 'Committed rubric the AI follows when reviewing PRs.',
    rationale: 'L3 signal: the quality criteria for "is this PR ok" are now written down.',
    detection: { type: 'any-of', pattern: ['.github/review-rubric.md', 'docs/review-criteria.md', '.github/prompts/review.md', 'docs/qa/'] },
  },
  {
    id: 'acmm:quality-dashboard',
    source: 'acmm',
    level: 3,
    category: 'observability',
    name: 'Quality dashboard',
    description: 'A dashboard or page that renders the AI loop metrics.',
    rationale: 'L3 visibility: metrics you can see are the ones that get acted on.',
    detection: { type: 'any-of', pattern: ['web/public/analytics.js', 'web/src/components/analytics/'] },
    referencePath: 'web/public/analytics.js',
  },
  {
    id: 'acmm:ci-matrix',
    source: 'acmm',
    level: 3,
    category: 'feedback-loop',
    name: 'CI matrix',
    description: 'Matrix CI testing multiple platforms/versions.',
    rationale: 'L3 breadth: coverage across the real deployment envelope.',
    detection: { type: 'any-of', pattern: ['.github/workflows/build.yml', '.github/workflows/ci.yml', '.github/workflows/test.yml'] },
  },

  // L4 — Adaptive: the loop closes
  {
    id: 'acmm:auto-qa-tuning',
    source: 'acmm',
    level: 4,
    category: 'feedback-loop',
    name: 'Auto-QA self-tuning config',
    description: 'A config file that tunes review prompts based on the L3 metrics.',
    rationale: 'L4 loop-closing signal: metrics feeding back into instructions automatically.',
    detection: { type: 'any-of', pattern: ['.github/auto-qa-tuning.json', '.github/qa-tuning.yml'] },
  },
  {
    id: 'acmm:nightly-compliance',
    source: 'acmm',
    level: 4,
    category: 'feedback-loop',
    name: 'Nightly compliance scan',
    description: 'Scheduled workflow that re-validates the codebase against its rules every night.',
    rationale: 'L4 drift detection: noticing when the loop itself has broken.',
    detection: { type: 'any-of', pattern: ['.github/workflows/nightly-compliance.yml', '.github/workflows/nightly.yml', '.github/workflows/nightly-test.yml', '.github/workflows/nightly-test-suite.yml'] },
  },
  {
    id: 'acmm:copilot-review-apply',
    source: 'acmm',
    level: 4,
    category: 'feedback-loop',
    name: 'Automated review application',
    description: 'Workflow that applies AI-review suggestions automatically to PRs.',
    rationale: 'L4 action-taking: the loop closes when suggestions become commits without human intervention.',
    detection: { type: 'any-of', pattern: ['.github/workflows/copilot-review-apply.yml', '.github/workflows/ai-fix.yml', '.github/workflows/auto-review.yml'] },
  },
  {
    id: 'acmm:auto-label',
    source: 'acmm',
    level: 4,
    category: 'feedback-loop',
    name: 'Automated issue labeling',
    description: 'Workflow or bot config that triages new issues with AI.',
    rationale: 'L4 triage automation: removes a human step from the default path.',
    detection: { type: 'any-of', pattern: ['.github/workflows/auto-label.yml', '.github/labeler.yml', '.github/workflows/triage.yml'] },
  },
  {
    id: 'acmm:ai-fix-workflow',
    source: 'acmm',
    level: 4,
    category: 'feedback-loop',
    name: 'AI-fix-requested workflow',
    description: 'A workflow or label that dispatches AI agents on issues marked for fix.',
    rationale: 'L4 intent channel: humans express "fix this" as data; the loop executes.',
    detection: { type: 'any-of', pattern: ['.github/workflows/ai-fix.yml', '.github/workflows/fix-requested.yml'] },
  },
  {
    id: 'acmm:tier-classifier',
    source: 'acmm',
    level: 4,
    category: 'governance',
    name: 'Change-tier classifier',
    description: 'Workflow that classifies PRs by risk/blast-radius and routes review accordingly.',
    rationale: 'L4 risk-aware routing: not every change gets the same scrutiny.',
    detection: { type: 'any-of', pattern: ['.github/workflows/tier-classifier.yml', '.github/workflows/pr-size.yml'] },
  },
  {
    id: 'acmm:security-ai-md',
    source: 'acmm',
    level: 4,
    category: 'governance',
    name: 'AI security policy',
    description: 'A SECURITY-AI.md or equivalent defining what the AI is and is not allowed to do.',
    rationale: 'L4 policy: the rules the self-tuning system cannot override.',
    detection: { type: 'any-of', pattern: ['SECURITY-AI.md', 'docs/security/SECURITY-AI.md', 'docs/SECURITY-AI.md'] },
    referencePath: 'docs/security/SECURITY-AI.md',
  },

  // L5 — Self-Sustaining: the codebase acts on its own behalf
  {
    id: 'acmm:auto-issue-gen',
    source: 'acmm',
    level: 5,
    category: 'feedback-loop',
    name: 'Automated issue generation',
    description: 'Workflow or cron that generates work items for the AI to pick up.',
    rationale: 'L5 self-direction: the codebase proposes its own next task.',
    detection: { type: 'any-of', pattern: ['.github/workflows/auto-issue.yml', '.github/workflows/issue-gen.yml', '.github/workflows/auto-generate-issues.yml'] },
  },
  {
    id: 'acmm:multi-agent-orchestration',
    source: 'acmm',
    level: 5,
    category: 'feedback-loop',
    name: 'Multi-agent orchestration',
    description: 'A workflow or script that coordinates multiple AI agents on one task.',
    rationale: 'L5 composition: single agents become units of a larger autonomous system.',
    detection: { type: 'any-of', pattern: ['scripts/orchestrate.mjs', '.github/workflows/orchestrate.yml', 'orchestrator/'] },
  },
  {
    id: 'acmm:strategic-dashboard',
    source: 'acmm',
    level: 5,
    category: 'observability',
    name: 'Strategic dashboard',
    description: 'A human-facing dashboard that shows *what the codebase is doing on its own*.',
    rationale: 'L5 accountability: humans need visibility into autonomous behavior without micromanaging it.',
    detection: { type: 'any-of', pattern: ['web/src/components/acmm/', 'web/public/analytics.js', 'docs/autonomous-work-log.md'] },
  },
  {
    id: 'acmm:merge-queue',
    source: 'acmm',
    level: 5,
    category: 'feedback-loop',
    name: 'Merge queue / auto-merge',
    description: 'Branch protection with automated merge queue or tide-style auto-merge.',
    rationale: 'L5 throughput: humans no longer gate individual merges, only the queue config.',
    detection: { type: 'any-of', pattern: ['.github/workflows/merge-queue.yml', '.prow.yaml', 'tide.yaml'] },
  },
  {
    id: 'acmm:policy-as-code',
    source: 'acmm',
    level: 5,
    category: 'governance',
    name: 'Policy as code',
    description: 'Policies expressed as machine-enforceable code (OPA, ConfTest, etc.).',
    rationale: 'L5 self-enforcing constraints: policies that cannot drift because they are executed.',
    detection: { type: 'any-of', pattern: ['.github/policies/', 'policy/', 'conftest.yaml', 'opa/'] },
  },
  {
    id: 'acmm:public-metrics',
    source: 'acmm',
    level: 5,
    category: 'observability',
    name: 'Public metrics endpoint',
    description: 'A published metrics endpoint or analytics page that external reviewers can audit.',
    rationale: 'L5 external accountability: the self-running codebase must be inspectable from outside.',
    detection: { type: 'any-of', pattern: ['web/netlify/functions/analytics-accm.mts', 'web/public/analytics.js'] },
  },
  {
    id: 'acmm:reflection-log',
    source: 'acmm',
    level: 5,
    category: 'feedback-loop',
    name: 'Reflection log',
    description: 'A committed log where the AI records lessons learned that feed back into instruction files.',
    rationale: 'L5 self-improvement loop: the codebase records what changed its own behavior.',
    detection: { type: 'any-of', pattern: ['docs/reflections/', 'memory/', '.memory/', 'REFLECTIONS.md'] },
  },
]

export const acmmSource: Source = {
  id: 'acmm',
  name: 'AI Codebase Maturity Model',
  url: 'https://arxiv.org/abs/2604.09388',
  citation: 'Anderson, A. (2026). The AI Codebase Maturity Model. arXiv:2604.09388',
  definesLevels: true,
  levels: LEVELS,
  criteria: CRITERIA,
}
