/**
 * ACMM L4–L6 criteria definitions.
 *
 * Extracted from acmm.ts — see issue #15790 / #21610.
 */
import type { Criterion } from './types'

export const CRITERIA_L4_L6: Criterion[] = [
  // ── L4 — Adaptive / Structured ──────────────────────────────────
  { id: 'acmm:auto-qa-tuning', source: 'acmm', level: 4, category: 'self-tuning', name: 'Auto-QA self-tuning config', description: 'A config file that tunes review prompts based on the L3 metrics.', rationale: 'L4 loop-closing signal: metrics feeding back into instructions automatically.', details: 'An auto-QA tuning config adjusts review strictness and prompt templates based on your L3 metrics.', detection: { type: 'any-of', pattern: ['.github/auto-qa-tuning.json', '.github/qa-tuning.yml'] } },
  { id: 'acmm:nightly-compliance', source: 'acmm', level: 4, category: 'feedback-loop', name: 'Nightly compliance scan', description: 'Scheduled workflow that re-validates the codebase against its rules every night.', rationale: 'L4 drift detection: noticing when the loop itself has broken.', details: 'A nightly compliance scan is a scheduled CI workflow that runs your full test suite, linters, and security checks on a cron schedule.', detection: { type: 'any-of', pattern: ['.github/workflows/nightly-compliance.yml', '.github/workflows/nightly.yml', '.github/workflows/nightly-test.yml', '.github/workflows/nightly-test-suite.yml', '.context/cron/', 'cron-registry.yaml', '.context/cron/agentic-audit.crontab'] } },
  { id: 'acmm:copilot-review-apply', source: 'acmm', level: 4, category: 'feedback-loop', name: 'Automated review application', description: 'Workflow that applies AI-review suggestions automatically to PRs.', rationale: 'L4 action-taking: the loop closes when suggestions become commits without human intervention.', details: 'Automated review application is a workflow that takes AI-generated review comments and applies the suggested fixes directly as commits on the PR branch.', detection: { type: 'any-of', pattern: ['.github/workflows/copilot-review-apply.yml', '.github/workflows/ai-fix.yml', '.github/workflows/auto-review.yml'] } },
  { id: 'acmm:auto-label', source: 'acmm', level: 4, category: 'feedback-loop', name: 'Automated issue labeling', description: 'Workflow or bot config that triages new issues with AI.', rationale: 'L4 triage automation: removes a human step from the default path.', details: 'Automated issue labeling uses AI or pattern-matching rules to classify new issues with labels the moment they are filed.', detection: { type: 'any-of', pattern: ['.github/workflows/auto-label.yml', '.github/labeler.yml', '.github/workflows/triage.yml'] } },
  { id: 'acmm:ai-fix-workflow', source: 'acmm', level: 4, category: 'feedback-loop', name: 'AI-fix-requested workflow', description: 'A workflow or label that dispatches AI agents on issues marked for fix.', rationale: 'L4 intent channel: humans express "fix this" as data; the loop executes.', details: 'An AI-fix-requested workflow watches for a specific label on issues and automatically dispatches an AI agent to attempt a fix, create a branch, and open a PR.', detection: { type: 'any-of', pattern: ['.github/workflows/ai-fix.yml', '.github/workflows/fix-requested.yml', '.github/workflows/claude.yml'] } },
  { id: 'acmm:tier-classifier', source: 'acmm', level: 4, category: 'governance', name: 'Change classification policy', description: 'Workflow or policy that classifies changes by risk tier and routes review accordingly.', rationale: 'L4 risk-aware routing: not every change gets the same scrutiny.', details: 'A change-tier classifier analyzes each PR\'s files, size, and content to assign a risk tier.', detection: { type: 'any-of', pattern: ['.github/workflows/tier-classifier.yml', '.github/workflows/pr-size.yml'] } },
  { id: 'acmm:security-ai-md', source: 'acmm', level: 4, category: 'governance', name: 'AI security policy', description: 'A SECURITY-AI.md or equivalent defining what the AI is and is not allowed to do.', rationale: 'L4 policy: the rules the self-tuning system cannot override.', details: 'SECURITY-AI.md is a policy document that defines hard boundaries for AI agents.', detection: { type: 'any-of', pattern: ['SECURITY-AI.md', 'docs/security/SECURITY-AI.md', 'docs/SECURITY-AI.md'] }, referencePath: 'docs/security/SECURITY-AI.md' },
  { id: 'acmm:structured-workflows', source: 'acmm', level: 4, category: 'feedback-loop', name: 'Structured workflow skills', description: 'Skills that encode complex decision logic as repeatable workflows with phases, branching, and sub-skill delegation.', rationale: 'Go beyond simple checklists by using decision trees, convergence loops, and environment-aware routing.', scannable: false, details: 'A TDD skill that routes based on input type and environment.', detection: { type: 'any-of', pattern: ['.claude/skills/', '.claude/commands/'] } },
  { id: 'acmm:router-skills', source: 'acmm', level: 4, category: 'feedback-loop', name: 'Router skills with decision trees', description: 'Parent skills contain mermaid flowcharts as executable workflow logic.', rationale: 'The model traverses the graph based on context rather than improvising differently each session.', scannable: false, details: 'A TDD skill with a mermaid diagram routing based on input type and cluster availability.', detection: { type: 'any-of', pattern: ['.claude/skills/', '.claude/commands/'] } },
  { id: 'acmm:tdd-workflows', source: 'acmm', level: 4, category: 'feedback-loop', name: 'TDD workflows with environment routing', description: 'Structured test-first cycle that dispatches to the correct test environment and loops until tests pass.', rationale: 'Mechanical commit gates ensure tests improve between commits.', scannable: false, details: 'Reads the issue, creates a worktree, enters the TDD loop, and routes to the appropriate cluster or CI environment.', detection: { type: 'any-of', pattern: ['.claude/skills/', '.claude/commands/'] } },
  { id: 'acmm:structured-rca', source: 'acmm', level: 4, category: 'feedback-loop', name: 'Structured RCA workflows', description: 'Phased investigation that gathers evidence before diagnosing.', rationale: 'Prevents the AI from jumping to conclusions from the first error it sees.', scannable: false, details: 'A 6-phase skill: download artifacts, extract errors, reconstruct timeline, compare against last 10 runs, classify, produce structured report.', detection: { type: 'any-of', pattern: ['.claude/skills/', '.claude/commands/'] } },
  { id: 'acmm:multi-perspective-review', source: 'acmm', level: 4, category: 'feedback-loop', name: 'Multi-perspective review', description: 'Multiple independent review perspectives dispatched in parallel with a convergence loop.', rationale: 'Findings tallied independently and a convergence loop until zero critical issues remain.', scannable: false, details: 'Dispatches 8 perspectives using haiku-tier agents. Independently counts findings, loops through fix-and-re-review until convergence.', detection: { type: 'any-of', pattern: ['.claude/skills/', '.claude/commands/'] } },
  { id: 'acmm:idempotent-workflows', source: 'acmm', level: 4, category: 'readiness', name: 'Idempotent and resumable workflows', description: 'Workflows derive state from durable infrastructure rather than session memory.', rationale: 'A new session picks up where the last one left off without explanation.', scannable: false, details: 'A TDD skill that checks gh pr checks and git log at startup to determine current state.', detection: { type: 'path', pattern: 'CLAUDE.md' } },
  { id: 'acmm:session-continuity', source: 'acmm', level: 4, category: 'learning', name: 'Session continuity', description: 'A persistent record the agent reads at session start to recover prior context.', rationale: 'Bridges the gap between what git/CI can tell you and what can\'t be derived.', details: 'A .claude/checkpoint.md recording current branch, active worktree, plan path, completed tasks, and remaining steps.', scannable: false, detection: { type: 'any-of', pattern: ['.claude/checkpoint.md', '.claude/session-summary.md'] }, crossCutting: 'learning' },
  { id: 'acmm:cross-session-knowledge', source: 'acmm', level: 4, category: 'learning', name: 'Cross-session knowledge sharing', description: 'A git-committed knowledge store that shares learnings across sessions, users, and crashes.', rationale: 'Accumulates institutional knowledge that any developer\'s session can read at startup.', details: 'A knowledge.jsonl committed to the repo where each entry records a learning.', scannable: false, detection: { type: 'any-of', pattern: ['knowledge.jsonl', '.knowledge/', 'docs/reflections/'] }, crossCutting: 'learning' },
  { id: 'acmm:cross-repo-skills', source: 'acmm', level: 4, category: 'readiness', name: 'Cross-repository skill sharing', description: 'A mechanism for distributing skills, safety configuration, and conventions across multiple repos.', rationale: 'Skills stay consistent across repos without manual duplication.', scannable: false, details: 'A private GitHub repo acting as a plugin marketplace. Consuming repos install shared skills via a marketplace command.', detection: { type: 'path', pattern: '.claude/settings.json' } },
  { id: 'acmm:github-coordination', source: 'acmm', level: 4, category: 'readiness', name: 'GitHub as coordination layer', description: 'Using GitHub issues, PRs, and @mentions as the sole coordination system.', rationale: 'No parallel tracking system — the repo\'s native tools are the single source of truth.', scannable: false, details: 'CI failures create GitHub issues automatically. Developers and AI coordinate through issue comments and PR reviews.', detection: { type: 'path', pattern: '.github/workflows/' } },
  { id: 'acmm:feedback-loops', source: 'acmm', level: 4, category: 'learning', name: 'Self-improving feedback loops', description: 'Systems that encode learnings from AI sessions back into the tooling.', rationale: 'Each learning gets routed to the right output channel.', scannable: false, details: 'A session retrospective skill that analyzes repeated commands, debugging cycles, and revert/fix chains.', detection: { type: 'path', pattern: 'CLAUDE.md' }, crossCutting: 'learning' },
  { id: 'acmm:claude-md-auto-sync', source: 'acmm', level: 4, category: 'learning', name: 'CLAUDE.md auto-sync', description: 'A workflow that syncs captured corrections and preferences into CLAUDE.md automatically.', rationale: 'Keeps instruction files current with accumulated learnings without manual editing.', scannable: false, details: 'A weekly workflow reviews new entries in the knowledge base and correction log, drafts updates to CLAUDE.md, and opens a PR.', detection: { type: 'any-of', pattern: ['.github/workflows/claude-md-sync.yml'] }, crossCutting: 'learning' },
  { id: 'acmm:preference-index', source: 'acmm', level: 4, category: 'learning', name: 'Preference index', description: 'A structured index of captured preferences keyed by topic or file area.', rationale: 'Allows the AI to look up relevant preferences without loading everything into context.', scannable: false, details: 'A preferences.json indexed by file path pattern.', detection: { type: 'any-of', pattern: ['preferences.json', '.claude/preferences.json'] }, crossCutting: 'learning' },
  { id: 'acmm:task-ledger', source: 'acmm', level: 4, category: 'traceability', name: 'Task traceability ledger', description: 'Every agent task is logged with intent, inputs, and outputs.', rationale: 'Creates an audit trail of what the AI was asked to do and what it did.', scannable: false, details: 'A JSONL log where each entry records: timestamp, task description, files read, files modified, commands run, test results, commit SHA.', detection: { type: 'any-of', pattern: ['task-log.jsonl', '.claude/task-log.jsonl'] }, crossCutting: 'traceability' },

  // ── L5 — Semi-Automated ────────────────────────────
  { id: 'acmm:github-actions-ai', source: 'acmm', level: 5, category: 'feedback-loop', name: 'GitHub Actions AI integration', description: 'GitHub Actions trigger AI-assisted workflows automatically on CI failures, PR events, or @claude mentions.', rationale: 'Detection and proposed resolution happen without human initiation.', details: 'A claude.yml workflow triggers on @claude mentions in issues and PR comments.', detection: { type: 'any-of', pattern: ['.github/workflows/claude.yml', '.github/workflows/claude-code-review.yml'] } },
  { id: 'acmm:auto-qa-self-tuning', source: 'acmm', level: 5, category: 'self-tuning', name: 'Auto-QA with self-tuning', description: 'An automated quality system that tracks suggestion acceptance rates and adjusts its own sensitivity thresholds.', rationale: 'The system improves its own review quality without human tuning.', details: 'An auto-qa workflow runs 4x/day. The companion auto-qa-tuner tracks acceptance rates.', detection: { type: 'any-of', pattern: ['.github/workflows/auto-qa.yml', '.github/auto-qa-tuning.json'] } },
  { id: 'acmm:public-metrics', source: 'acmm', level: 5, category: 'observability', name: 'Public metrics endpoint', description: 'A published metrics endpoint or analytics page that external reviewers can audit.', rationale: 'The self-running codebase must be inspectable from outside.', details: 'A public metrics endpoint exposes your project\'s health and maturity metrics to external stakeholders.', detection: { type: 'any-of', pattern: ['web/netlify/functions/analytics-accm.mts', 'web/public/analytics.js'] } },
  { id: 'acmm:policy-as-code', source: 'acmm', level: 5, category: 'governance', name: 'Policy as code', description: 'Policies expressed as machine-enforceable code (OPA, ConfTest, etc.).', rationale: 'Policies that cannot drift because they are executed, not documented.', details: 'Policy as code means your governance rules are written as executable code using tools like OPA or ConfTest.', detection: { type: 'any-of', pattern: ['.github/policies/', 'policy/', 'conftest.yaml', 'opa/'] } },
  { id: 'acmm:reflection-log', source: 'acmm', level: 5, category: 'feedback-loop', name: 'Reflection log', description: 'A committed log where the AI records lessons learned that feed back into instruction files.', rationale: 'The codebase records what changed its own behavior.', details: 'A reflection log is a committed file or directory where AI agents record what they learned during a session.', detection: { type: 'any-of', pattern: ['docs/reflections/', 'memory/', '.memory/', 'REFLECTIONS.md'] }, crossCutting: 'learning' },
  { id: 'acmm:periodic-reflection', source: 'acmm', level: 5, category: 'learning', name: 'Periodic reflection review', description: 'A scheduled job that surfaces captured reflections for human review and pruning.', rationale: 'Prevents the knowledge base from growing stale.', scannable: false, details: 'A monthly cron posts a summary of new knowledge base entries for the team to review, confirm, and prune.', detection: { type: 'any-of', pattern: ['.github/workflows/reflection-review.yml'] }, crossCutting: 'learning' },
  { id: 'acmm:audit-trail', source: 'acmm', level: 5, category: 'traceability', name: 'Audit trail workflow', description: 'A workflow that records agent-generated PRs and attributes them for later review.', rationale: 'Distinguishes human-authored from AI-authored changes.', details: 'A GitHub Action that adds a label (ai-generated) to PRs created by AI, and appends session statistics as a PR comment.', detection: { type: 'any-of', pattern: ['.github/workflows/audit-trail.yml', '.github/workflows/ai-attribution.yml'] }, crossCutting: 'traceability' },

  // ── L6 — Autonomous ─────────────────────────────────────────────
  { id: 'acmm:auto-issue-gen', source: 'acmm', level: 6, category: 'autonomy', name: 'Automated issue generation', description: 'Workflow or cron that generates work items for the AI to pick up — the system identifies its own problems and creates tasks.', rationale: 'L6 self-direction: the codebase proposes its own next task.', details: 'Automated issue generation is a cron-triggered workflow that scans the codebase for TODOs, stale dependencies, failing tests, or coverage gaps and files GitHub issues for each finding.', detection: { type: 'any-of', pattern: ['.github/workflows/auto-issue.yml', '.github/workflows/issue-gen.yml', '.github/workflows/auto-generate-issues.yml'] } },
  { id: 'acmm:multi-agent-orchestration', source: 'acmm', level: 6, category: 'autonomy', name: 'Multi-agent orchestration', description: 'A workflow or script that coordinates multiple AI agents on one task, decomposing work and managing parallel execution.', rationale: 'L6 composition: single agents become units of a larger autonomous system.', details: 'Multi-agent orchestration uses a dispatcher script or workflow to coordinate multiple AI agents working on different parts of one task.', detection: { type: 'any-of', pattern: ['scripts/orchestrate.mjs', '.github/workflows/orchestrate.yml', 'orchestrator/', '.mcp.json', 'agents/dispatch/', 'tl-dispatch.sh', '.framework.yaml', '.termlink-task'] } },
  { id: 'acmm:merge-queue', source: 'acmm', level: 6, category: 'autonomy', name: 'Merge queue / auto-merge', description: 'Branch protection with automated merge queue, allowing verified AI-generated PRs to merge without manual intervention.', rationale: 'L6 throughput: humans no longer gate individual merges, only the queue config.', details: 'A merge queue automatically batches, tests, and merges approved PRs in dependency order without human intervention.', detection: { type: 'any-of', pattern: ['.github/workflows/merge-queue.yml', '.prow.yaml', 'tide.yaml'] } },
  { id: 'acmm:strategic-dashboard', source: 'acmm', level: 6, category: 'observability', name: 'Strategic dashboard', description: 'A human-facing dashboard that shows what the codebase is doing on its own — active AI sessions, pending fixes, merge pipeline, trend data.', rationale: 'L6 accountability: humans need visibility into autonomous behavior without micromanaging it.', details: 'A strategic dashboard shows humans what the autonomous system is doing: which issues it generated, which fixes it attempted, which PRs it merged.', detection: { type: 'any-of', pattern: ['web/src/components/acmm/', 'web/public/analytics.js', 'docs/autonomous-work-log.md'] } },
  { id: 'acmm:risk-assessment-config', source: 'acmm', level: 6, category: 'governance', name: 'Risk assessment config', description: 'A config that lets the agent assess blast radius before acting — preventing autonomous changes to high-risk areas.', rationale: 'Without risk awareness, autonomous changes can touch production paths unchecked.', details: 'A config defining: high_risk: ["deploy/", "migrations/", "security/"] — changes to these paths require human review regardless of AI confidence.', detection: { type: 'any-of', pattern: ['risk-config.json', '.claude/risk-config.json', '.github/risk-assessment.yml', '.fabric/subsystems.yaml', '.fabric/components/', 'agents/fabric/'] } },
  { id: 'acmm:production-feedback', source: 'acmm', level: 6, category: 'feedback-loop', name: 'Production feedback signal', description: 'A mechanism that feeds production observations back into the development loop.', rationale: 'Closes the gap between deployment and development.', scannable: false, details: 'Error rates from production monitoring creating GitHub issues tagged production-regression, which trigger RCA workflows.', detection: { type: 'any-of', pattern: ['.github/workflows/production-feedback.yml'] } },
  { id: 'acmm:observability-runbook', source: 'acmm', level: 6, category: 'governance', name: 'Observability runbook', description: 'A runbook describing how humans debug autonomous behavior — what to check when the AI does something unexpected.', rationale: 'Humans need a guide for understanding and overriding autonomous decisions.', details: 'A docs/ai-ops-runbook.md covering: how to review agent session transcripts, trace a commit back to its trigger issue, and pause autonomous workflows.', detection: { type: 'any-of', pattern: ['docs/ai-ops-runbook.md', 'docs/runbook/', 'RUNBOOK.md'] } },
  { id: 'acmm:rollback-drill', source: 'acmm', level: 6, category: 'governance', name: 'Rollback drill', description: 'A documented or automated rollback procedure for when autonomous changes cause problems.', rationale: 'Autonomy without a kill switch is recklessness.', scannable: false, details: 'A documented procedure: "If a nightly AI-merged PR breaks production: (1) revert PR, (2) disable auto-merge, (3) file incident issue, (4) RCA workflow runs."', detection: { type: 'any-of', pattern: ['docs/rollback-drill.md', 'docs/ai-ops-runbook.md'] } },
]
