/**
 * ACMM L0–L3 criteria definitions.
 *
 * Extracted from acmm.ts — see issue #15790 / #21610.
 */
import type { Criterion } from './types'

export const CRITERIA_L0_L3: Criterion[] = [
  // ── L0 — Prerequisites ──────────────────────────────────────────
  { id: 'acmm:prereq-test-suite', source: 'acmm', level: 0, category: 'prerequisite', name: 'Automated test suite', description: 'A test runner config and at least one test directory.', rationale: 'Without tests, TDD workflows, coverage gates, and verify-before-reporting have nothing to run.', details: 'An automated test suite is a test framework (Vitest, Jest, pytest, go test, etc.) with a configuration file and at least one test directory.', detection: { type: 'any-of', pattern: ['vitest.config.ts', 'vitest.config.js', 'jest.config.js', 'jest.config.ts', 'go.mod', 'pytest.ini', 'pyproject.toml'] } },
  { id: 'acmm:prereq-e2e', source: 'acmm', level: 0, category: 'prerequisite', name: 'End-to-end tests', description: 'Playwright, Cypress, or equivalent E2E test suite that verifies the system works as a whole.', rationale: 'Unit tests catch code-level bugs but miss integration failures that only appear when components connect.', details: 'End-to-end tests use tools like Playwright or Cypress to simulate real user interactions.', detection: { type: 'any-of', pattern: ['playwright.config.ts', 'playwright.config.js', 'cypress.config.ts', 'cypress.config.js', 'e2e/', 'tests/e2e/'] } },
  { id: 'acmm:prereq-cicd', source: 'acmm', level: 0, category: 'prerequisite', name: 'CI/CD pipeline', description: 'A working CI/CD pipeline that runs on every PR.', rationale: 'The foundation for coverage gates, nightly scans, and automated review workflows.', details: 'A CI/CD pipeline runs build, test, and lint on every push and PR.', detection: { type: 'any-of', pattern: ['.github/workflows/', '.gitlab-ci.yml', 'Jenkinsfile', '.circleci/'] } },
  { id: 'acmm:prereq-pr-template', source: 'acmm', level: 0, category: 'prerequisite', name: 'Pull request template', description: 'Structured PR description template that guides both humans and AI when creating or reviewing PRs.', rationale: 'A template nudges every PR through the same reasoning — a structural aid for consistent contributions.', details: 'A PR template is a markdown form that pre-populates every new pull request with sections like Summary, Test Plan, and Breaking Changes.', detection: { type: 'any-of', pattern: ['.github/pull_request_template.md', '.github/PULL_REQUEST_TEMPLATE.md'] }, referencePath: '.github/pull_request_template.md' },
  { id: 'acmm:prereq-issue-template', source: 'acmm', level: 0, category: 'prerequisite', name: 'Issue template', description: 'Structured issue form that ensures every report is triageable by humans and AI.', rationale: 'Forces consistent issue shape so automation can classify and triage.', details: 'Issue templates are structured forms that ensure every new issue includes the fields needed for triage.', detection: { type: 'any-of', pattern: ['.github/ISSUE_TEMPLATE/', '.github/issue_template.md'] } },
  { id: 'acmm:prereq-contrib-guide', source: 'acmm', level: 0, category: 'prerequisite', name: 'Contributing guide', description: 'CONTRIBUTING.md used both by humans and AI to understand contribution rules, development setup, and workflow expectations.', rationale: 'Documented process is a signal the team has articulated how work enters the repo.', details: 'CONTRIBUTING.md documents how to set up the development environment, run tests, format code, and submit changes.', detection: { type: 'any-of', pattern: ['CONTRIBUTING.md', '.github/CONTRIBUTING.md'] } },
  { id: 'acmm:prereq-code-style', source: 'acmm', level: 0, category: 'prerequisite', name: 'Code style config', description: 'Committed formatter and linter configuration that enforces style mechanically rather than through instructions.', rationale: 'Style rules expressed as config — mechanized judgment.', details: 'A code style config file enforces formatting and linting rules automatically.', detection: { type: 'any-of', pattern: ['.eslintrc', '.eslintrc.json', '.eslintrc.js', 'eslint.config.js', '.prettierrc', 'ruff.toml', '.golangci.yml'] } },
  { id: 'acmm:prereq-coverage-gate', source: 'acmm', level: 0, category: 'prerequisite', name: 'Coverage gate workflow', description: 'CI workflow that fails PRs below a coverage threshold.', rationale: 'The first metric you encode as a blocking signal.', details: 'A coverage gate is a CI workflow that blocks merging when test coverage drops below a threshold.', detection: { type: 'any-of', pattern: ['.github/workflows/coverage-gate.yml', '.github/workflows/coverage.yml', '.coverage-thresholds.json'] }, referencePath: '.github/workflows/coverage-gate.yml' },

  // ── L2 — Instructed ─────────────────────────────────────────────
  { id: 'acmm:claude-md', source: 'acmm', level: 2, category: 'feedback-loop', name: 'CLAUDE.md instructions', description: 'Project-level instructions loaded by Claude Code at every session start.', rationale: 'The foundational L2 feedback loop: encoding judgment as text the AI reads every session.', details: 'CLAUDE.md is a file at the root of your repository that Claude Code reads automatically at the start of every session.', detection: { type: 'path', pattern: 'CLAUDE.md' }, referencePath: 'CLAUDE.md', frequency: 'Every AI session' },
  { id: 'acmm:copilot-instructions', source: 'acmm', level: 2, category: 'feedback-loop', name: 'Copilot instructions', description: 'GitHub Copilot repository instructions loaded on every Copilot interaction.', rationale: 'Same L2 signal as CLAUDE.md, scoped to Copilot users.', details: 'copilot-instructions.md is a file in .github/ that GitHub Copilot reads to understand your project-specific rules.', detection: { type: 'path', pattern: '.github/copilot-instructions.md' }, referencePath: '.github/copilot-instructions.md', frequency: 'Every Copilot session' },
  { id: 'acmm:agents-md', source: 'acmm', level: 2, category: 'feedback-loop', name: 'AGENTS.md shared directives', description: 'Cross-tool agent instructions readable by any AI coding tool.', rationale: 'Portable instructions that survive tool changes — an L2 durability signal.', details: 'AGENTS.md is a tool-agnostic instruction file that any AI coding agent can read.', detection: { type: 'path', pattern: 'AGENTS.md' }, frequency: 'Every AI session' },
  { id: 'acmm:cursor-rules', source: 'acmm', level: 2, category: 'feedback-loop', name: 'Cursor rules', description: 'Cursor IDE project rules that guide its agent.', rationale: 'Tool-specific L2 signal for Cursor users.', details: 'Cursor rules are project-level instruction files that the Cursor IDE reads to guide its AI agent.', detection: { type: 'any-of', pattern: ['.cursor/rules', '.cursorrules'] }, frequency: 'Every Cursor session' },
  { id: 'acmm:prompts-catalog', source: 'acmm', level: 2, category: 'feedback-loop', name: 'Prompt catalog', description: 'Committed prompt templates for recurring tasks.', rationale: 'Reusing prompts across the team turns tribal knowledge into shared L2 assets.', details: 'A prompt catalog is a directory of reusable prompt templates that encode your team\'s best approaches to recurring tasks.', detection: { type: 'any-of', pattern: ['prompts/', '.prompts/', 'docs/prompts/', '.github/prompts/', '.github/agents/'] } },
  { id: 'acmm:editor-config', source: 'acmm', level: 2, category: 'feedback-loop', name: 'EditorConfig', description: '.editorconfig for cross-editor consistency.', rationale: 'Baseline L2 consistency signal — trivial to add, hard to retrofit.', details: 'EditorConfig is a simple dotfile that tells every editor and IDE to use the same indentation, line endings, and charset settings.', detection: { type: 'path', pattern: '.editorconfig' } },
  { id: 'acmm:simple-skills', source: 'acmm', level: 2, category: 'feedback-loop', name: 'Simple skills', description: 'Skills that capture common patterns as checklists, reference lookups, or common task sequences.', rationale: 'Lightweight skills document how to do recurring tasks rather than encoding complex decision logic.', details: 'Simple skills are checklists or step sequences for common tasks.', scannable: false, detection: { type: 'any-of', pattern: ['.claude/skills/', '.claude/commands/', 'skills/'] } },
  { id: 'acmm:correction-capture', source: 'acmm', level: 2, category: 'learning', name: 'Correction capture', description: 'A mechanism that captures user corrections during agent sessions and persists them so the same mistake isn\'t repeated.', rationale: 'Without capturing corrections, every session starts from the same mistakes.', details: 'When a user says "no, don\'t use that approach," the correction is appended to a persistent store that future sessions read.', scannable: false, detection: { type: 'any-of', pattern: ['.claude/memory/', '.memory/', 'corrections.jsonl'] }, crossCutting: 'learning' },
  { id: 'acmm:positive-reinforcement', source: 'acmm', level: 2, category: 'learning', name: 'Positive reinforcement capture', description: 'A mechanism that captures confirmations of non-obvious correct behavior, not just corrections.', rationale: 'Records what works, not just what doesn\'t — prevents the system from becoming overly cautious.', scannable: false, details: 'When a user says "yes, exactly like that" after a non-obvious approach, the reinforcement is captured and persisted for future sessions.', detection: { type: 'path', pattern: '.claude/memory/' }, crossCutting: 'learning' },

  // ── L3 — Measured / Enforced ────────────────────────────────────
  { id: 'acmm:pr-acceptance-metric', source: 'acmm', level: 3, category: 'feedback-loop', name: 'PR acceptance tracking', description: 'Scheduled job that tracks AI PR acceptance rate over time.', rationale: 'L3 meta-metric: measuring the feedback loop itself, not just the code.', details: 'PR acceptance tracking is a scheduled job that measures what percentage of AI-generated PRs are merged vs. rejected over time.', detection: { type: 'any-of', pattern: ['scripts/build-accm-history.mjs', '.github/workflows/accm-history-update.yml', 'scripts/pr-metrics.mjs'] }, referencePath: 'scripts/build-accm-history.mjs' },
  { id: 'acmm:pr-review-rubric', source: 'acmm', level: 3, category: 'feedback-loop', name: 'PR review rubric', description: 'Committed rubric the AI follows when reviewing PRs.', rationale: 'L3 signal: the quality criteria for "is this PR ok" are now written down.', details: 'A PR review rubric is a document listing the specific quality criteria reviewers should check.', detection: { type: 'any-of', pattern: ['.github/review-rubric.md', 'docs/review-criteria.md', '.github/prompts/review.md', 'docs/qa/'] } },
  { id: 'acmm:quality-dashboard', source: 'acmm', level: 3, category: 'observability', name: 'Quality dashboard', description: 'A dashboard or page that renders the AI loop metrics.', rationale: 'L3 visibility: metrics you can see are the ones that get acted on.', details: 'A quality dashboard is a visible page or widget that renders your AI loop metrics in one place.', detection: { type: 'any-of', pattern: ['web/public/analytics.js', 'web/src/components/analytics/', 'web/app.py', 'web/blueprints/', 'web/watchtower/'] }, referencePath: 'web/public/analytics.js' },
  { id: 'acmm:ci-matrix', source: 'acmm', level: 3, category: 'feedback-loop', name: 'CI matrix', description: 'Matrix CI testing multiple platforms/versions.', rationale: 'L3 breadth: coverage across the real deployment envelope.', details: 'A CI matrix runs your test suite across multiple combinations of OS, language version, and architecture.', detection: { type: 'any-of', pattern: ['.github/workflows/build.yml', '.github/workflows/build-deploy.yml', '.github/workflows/ci.yml', '.github/workflows/test.yml'] } },
  { id: 'acmm:layered-safety', source: 'acmm', level: 3, category: 'governance', name: 'Layered safety model', description: 'Multiple independent enforcement layers — each catches what the others miss.', rationale: 'No single layer (hooks, CI, permissions, credentials) is sufficient alone.', details: 'A layered safety model combines pre-commit hooks, settings.json deny lists, Claude Code hooks, CI pipelines, and scoped credentials.', scannable: false, detection: { type: 'any-of', pattern: ['.claude/settings.json', '.claude/settings.local.json'] } },
  { id: 'acmm:mechanical-enforcement', source: 'acmm', level: 3, category: 'governance', name: 'Mechanical enforcement', description: 'Rules enforced by settings.json permissions and Claude Code hooks, not just markdown instructions.', rationale: 'Instructions the AI may not follow in long sessions; hooks run every time without exception.', details: '.claude/settings.json controls command permissions. Claude Code hooks run automated scripts on events.', scannable: false, detection: { type: 'any-of', pattern: ['.claude/settings.json'] } },
  { id: 'acmm:context-budget', source: 'acmm', level: 3, category: 'readiness', name: 'Context budget management', description: 'Controlling how much of the AI\'s context window is consumed by command output, reference material, and verbose logs.', rationale: 'Uncontrolled output floods the context window, degrading reasoning quality.', scannable: false, details: 'Instead of running verbose commands directly, redirect output to files and dispatch subagents to analyze.', detection: { type: 'path', pattern: 'CLAUDE.md' } },
  { id: 'acmm:model-tiering', source: 'acmm', level: 3, category: 'readiness', name: 'Model tiering for subagents', description: 'Using cheaper models for mechanical tasks and reserving the session model for reasoning tasks.', rationale: 'Not every task needs the most capable model — tiering saves cost and context.', scannable: false, details: 'Review agents dispatched with haiku for pattern matching, sonnet for analysis, session model reserved for architectural decisions.', detection: { type: 'path', pattern: 'CLAUDE.md' } },
  { id: 'acmm:verify-before-reporting', source: 'acmm', level: 3, category: 'readiness', name: 'Verify-before-reporting practices', description: 'Workflows require the AI to show evidence before accepting completion claims.', rationale: 'Treat AI completion claims the way you\'d treat a junior developer saying "it\'s done."', scannable: false, details: 'A skill that requires "after making changes, run git diff and go test and include the output."', detection: { type: 'path', pattern: 'CLAUDE.md' } },
  { id: 'acmm:evidence-antipatterns', source: 'acmm', level: 3, category: 'governance', name: 'Evidence-based antipattern rules', description: 'Numbered coding rules where every rule traces to a real bug with a PR or issue number.', rationale: 'Rules without evidence are opinions; rules with evidence are lessons.', scannable: false, details: 'Each rule includes: the pattern to avoid, the PR/issue where it caused a bug, a concrete grep check, and a severity tier.', detection: { type: 'path', pattern: 'CLAUDE.md' } },
  { id: 'acmm:session-summary', source: 'acmm', level: 3, category: 'learning', name: 'Session summary artifact', description: 'An end-of-session artifact that records what changed, what was tried, and what was learned.', rationale: 'Provides handoff context for the next session or developer.', details: 'A Stop hook writes to .claude/session-summary.md: branch, files changed, tests added, approaches tried, open questions.', scannable: false, detection: { type: 'any-of', pattern: ['.claude/session-summary.md', '.claude/checkpoint.md'] }, crossCutting: 'learning' },
  { id: 'acmm:structural-gates', source: 'acmm', level: 3, category: 'traceability', name: 'Structural gates', description: 'Config-enforced gates that block agents from touching protected areas without review.', rationale: 'Regardless of what the AI thinks it should do, some paths require human approval.', details: 'A settings.json deny list blocking writes to deploy/production/, migrations/, and .github/workflows/.', scannable: false, detection: { type: 'any-of', pattern: ['.claude/settings.json'] }, crossCutting: 'traceability' },
]
