/**
 * Resource hook registrations for the unified card system.
 */

import {
  useCachedPodIssues,
  useCachedEvents,
  useCachedDeployments,
  useCachedDeploymentIssues,
  useCachedHPAs,
  useCachedReplicaSets,
  useCachedStatefulSets,
  useCachedDaemonSets,
  useCachedCronJobs,
} from '../../../hooks/useCachedData'
import {
  useClusters,
  usePVCs,
  useServices,
  useOperators,
  useHelmReleases,
  useConfigMaps,
  useSecrets,
  useIngresses,
  useNodes,
  useJobs,
  useCronJobs,
  useStatefulSets,
  useDaemonSets,
  useHPAs,
  useReplicaSets,
  usePVs,
  useResourceQuotas,
  useLimitRanges,
  useNetworkPolicies,
  useNamespaces,
  useOperatorSubscriptions,
  useServiceAccounts,
  useK8sRoles,
  useK8sRoleBindings,
} from '../../../hooks/mcp'
import {
  useServiceExports,
  useServiceImports,
} from '../../../hooks/useMCS'
import type { ResourceHookConfig } from './factory'

export const RESOURCE_HOOKS: Array<ResourceHookConfig & { name: string }> = [
  { name: 'useCachedPodIssues', useHook: useCachedPodIssues, dataField: 'data', arity: 'cluster+namespace', wrapRefetch: true },
  { name: 'useCachedEvents', useHook: useCachedEvents, dataField: 'data', arity: 'cluster+namespace', wrapRefetch: true },
  { name: 'useCachedDeployments', useHook: useCachedDeployments, dataField: 'data', arity: 'cluster+namespace', wrapRefetch: true },
  { name: 'useCachedHPAs', useHook: useCachedHPAs, dataField: 'hpas', arity: 'cluster+namespace', wrapRefetch: true, extra: (result) => ({ isDemoData: (result as unknown as Record<string, unknown>).isDemoFallback }) },
  { name: 'useCachedReplicaSets', useHook: useCachedReplicaSets, dataField: 'replicasets', arity: 'cluster+namespace', wrapRefetch: true, extra: (result) => ({ isDemoData: (result as unknown as Record<string, unknown>).isDemoFallback }) },
  { name: 'useCachedStatefulSets', useHook: useCachedStatefulSets, dataField: 'statefulsets', arity: 'cluster+namespace', wrapRefetch: true, extra: (result) => ({ isDemoData: (result as unknown as Record<string, unknown>).isDemoFallback }) },
  { name: 'useCachedDaemonSets', useHook: useCachedDaemonSets, dataField: 'daemonsets', arity: 'cluster+namespace', wrapRefetch: true, extra: (result) => ({ isDemoData: (result as unknown as Record<string, unknown>).isDemoFallback }) },
  { name: 'useCachedCronJobs', useHook: useCachedCronJobs, dataField: 'cronjobs', arity: 'cluster+namespace', wrapRefetch: true, extra: (result) => ({ isDemoData: (result as unknown as Record<string, unknown>).isDemoFallback }) },
  { name: 'useClusters', useHook: useClusters, dataField: 'clusters', arity: 'none' },
  { name: 'usePVCs', useHook: usePVCs, dataField: 'pvcs', arity: 'cluster+namespace' },
  { name: 'useServices', useHook: useServices, dataField: 'services', arity: 'cluster+namespace' },
  { name: 'useCachedDeploymentIssues', useHook: useCachedDeploymentIssues, dataField: 'issues', arity: 'cluster+namespace', dataFallback: [] },
  { name: 'useOperators', useHook: useOperators, dataField: 'operators', arity: 'cluster' },
  { name: 'useHelmReleases', useHook: useHelmReleases, dataField: 'releases', arity: 'cluster' },
  { name: 'useConfigMaps', useHook: useConfigMaps, dataField: 'configmaps', arity: 'cluster+namespace' },
  { name: 'useSecrets', useHook: useSecrets, dataField: 'secrets', arity: 'cluster+namespace' },
  { name: 'useIngresses', useHook: useIngresses, dataField: 'ingresses', arity: 'cluster+namespace', extra: (result) => ({ isDemoData: (result as unknown as Record<string, unknown>).isDemoFallback }) },
  { name: 'useNodes', useHook: useNodes, dataField: 'nodes', arity: 'cluster' },
  { name: 'useJobs', useHook: useJobs, dataField: 'jobs', arity: 'cluster+namespace' },
  { name: 'useCronJobs', useHook: useCronJobs, dataField: 'cronJobs', arity: 'cluster+namespace' },
  { name: 'useStatefulSets', useHook: useStatefulSets, dataField: 'statefulSets', arity: 'cluster+namespace' },
  { name: 'useDaemonSets', useHook: useDaemonSets, dataField: 'daemonSets', arity: 'cluster+namespace' },
  { name: 'useHPAs', useHook: useHPAs, dataField: 'hpas', arity: 'cluster+namespace' },
  { name: 'useReplicaSets', useHook: useReplicaSets, dataField: 'replicaSets', arity: 'cluster+namespace' },
  { name: 'usePVs', useHook: usePVs, dataField: 'pvs', arity: 'cluster' },
  { name: 'useResourceQuotas', useHook: useResourceQuotas, dataField: 'resourceQuotas', arity: 'cluster+namespace', extra: (result) => ({ isDemoData: (result as unknown as Record<string, unknown>).isDemoFallback }) },
  { name: 'useLimitRanges', useHook: useLimitRanges, dataField: 'limitRanges', arity: 'cluster+namespace' },
  { name: 'useNetworkPolicies', useHook: useNetworkPolicies, dataField: 'networkpolicies', arity: 'cluster+namespace' },
  { name: 'useNamespaces', useHook: useNamespaces, dataField: 'namespaces', arity: 'cluster' },
  { name: 'useOperatorSubscriptions', useHook: useOperatorSubscriptions, dataField: 'subscriptions', arity: 'cluster' },
  { name: 'useServiceAccounts', useHook: useServiceAccounts, dataField: 'serviceAccounts', arity: 'cluster+namespace' },
  { name: 'useK8sRoles', useHook: useK8sRoles, dataField: 'roles', arity: 'cluster+namespace' },
  { name: 'useK8sRoleBindings', useHook: useK8sRoleBindings, dataField: 'bindings', arity: 'cluster+namespace' },
  { name: 'useServiceExports', useHook: useServiceExports, dataField: 'exports', arity: 'cluster+namespace' },
  { name: 'useServiceImports', useHook: useServiceImports, dataField: 'imports', arity: 'cluster+namespace' },
]
