export const EVENT_CARD_ACTIONS_CLASS = 'flex flex-wrap gap-2 mt-2'
export const EVENT_CARD_BUTTON_STYLE = { background: 'none', border: '1px solid var(--s-border-muted)', borderRadius: 'var(--s-rs)', color: 'var(--s-text-muted)', cursor: 'pointer' } as const
export const EVENT_CARD_CONTAINER_BASE_STYLE = { borderRadius: 'var(--s-r)', cursor: 'pointer' as const, transition: 'background 0.1s ease' }
export const EVENT_CARD_TITLE_STYLE = { fontWeight: 600, color: 'var(--s-text)', flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const }
export const EVENT_CARD_BADGE_BASE_STYLE = { fontWeight: 700, letterSpacing: '0.05em', textTransform: 'uppercase' as const, borderRadius: 8, flexShrink: 0 }
export const EVENT_CARD_DETAILS_TEXT_STYLE = { color: 'var(--s-text-dim)', flexShrink: 0 }
export const EVENT_CARD_TIME_STYLE = { flexShrink: 0 }
export const EVENT_CARD_TAG_STYLE = { borderRadius: 6, background: 'var(--s-surface)', color: 'var(--s-text-muted)', border: '1px solid var(--s-border-muted)' }
export const EVENT_CARD_REASON_STYLE = { lineHeight: 1.5, fontStyle: 'italic' as const, opacity: 0.85 }
export const EVENT_CARD_SOLVE_STATUS_LABEL_STYLE = { fontWeight: 600, flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const }
export const EVENT_CARD_COUNTDOWN_STYLE = { background: 'color-mix(in srgb, var(--s-info) 10%, transparent)', color: 'var(--s-info)', border: '1px solid color-mix(in srgb, var(--s-info) 30%, transparent)', flexShrink: 0 }
export const EVENT_CARD_PERCENT_STYLE = { flexShrink: 0 }
export const EVENT_CARD_PROGRESS_CONTAINER_STYLE = { height: 3, background: 'var(--s-border-muted)', borderRadius: 2, overflow: 'hidden' as const }
export const EVENT_CARD_PROGRESS_BAR_STYLE = { height: '100%', transition: 'width 0.35s ease' }
export const EVENT_CARD_MONITORING_BADGE_STYLE = { color: 'var(--s-warning)', background: 'rgba(227,179,65,0.08)', border: '1px solid rgba(227,179,65,0.28)' }
export const EVENT_CARD_MUTED_TEXT_STYLE = { color: 'var(--s-text-muted)' }
export const EVENT_CARD_ATTEMPT_BADGE_STYLE = { color: 'var(--s-text-muted)', paddingTop: 1, paddingBottom: 1, background: 'var(--s-surface)', border: '1px solid var(--s-border-muted)' }
export const EVENT_CARD_BODY_STYLE = { color: 'var(--s-text-muted)', lineHeight: 1.55 }
export const EVENT_CARD_ESCALATE_BUTTON_STYLE = { background: 'rgba(227,179,65,0.1)', border: '1px solid var(--s-warning)', borderRadius: 'var(--s-rs)', color: 'var(--s-warning)', cursor: 'pointer' as const, fontWeight: 600 }
export const EVENT_CARD_AUTO_HANDLING_STYLE = { color: 'var(--s-text-dim)', fontStyle: 'italic' as const, alignSelf: 'center' as const }
