export const RSS_UI_STRINGS = {
  defaultFeedName: 'Custom Feed',
  selectFeed: 'Select Feed',
  feedThumbnailAlt: 'Feed thumbnail',
  unknownSource: 'Unknown source',
  feedFallbackName: 'Feed',
  filterPrefix: 'Filter:',
  includeTermsPlaceholder: 'kubernetes, docker, cloud...',
  excludeTermsPlaceholder: 'spam, politics, off-topic...',
  sourceFilterTitle: 'Filter by source feed',
  feedUrlPlaceholder: 'Feed URL (e.g., r/kubernetes or hnrss.org/frontpage)',
  feedNamePlaceholder: 'Name (optional)',
  feedExamples: 'Examples: r/kubernetes, r/devops, hnrss.org/frontpage, techcrunch.com/feed',
  aggregateBadge: '(agg)',
  editAggregateTitle: 'Edit aggregate',
  removeFavoriteTitle: 'Remove from favorites',
  aggregateNamePlaceholder: 'Aggregate name (e.g., My Tech News)',
  aggregateIncludePlaceholder: 'kubernetes, AI, cloud...',
  aggregateExcludePlaceholder: 'spam, off-topic...',
  aggregateLabel: 'Aggregate',
  sourcesLabel: 'sources',
  demoAggregateName: 'Platform Watch',
} as const
