/**
 * Template generators for widget code generation
 * Contains render function generators for each card type
 */

import { WIDGET_CARDS, WIDGET_STATS, WIDGET_TEMPLATES } from './widgetRegistry'
import { generateWidgetStyles, generateWidgetShell } from './styleConverter'
import { resolveWidgetEndpoint, generateWidgetCommand } from './codeGenerator.utils'
import { generateCardRenderFunction } from './templates/cardRenderFunction'

export * from './templates/shared'
export * from './templates/clusterCards'
export * from './templates/infrastructureCards'
export * from './templates/cicdCards'
export * from './templates/cardRenderFunction'

// Generate Übersicht widget code for a single card
export function generateCardWidget(
  cardType: string,
  apiEndpoint: string,
  refreshInterval: number = 30000
): string {
  const card = WIDGET_CARDS[cardType]
  if (!card) {
    throw new Error(`Unknown card type: ${cardType}`)
  }

  const baseUrl = resolveWidgetEndpoint(apiEndpoint, card.apiEndpoints[0])
  /** Append source param so the backend can attribute traffic from exported widgets */
  const curlUrl = baseUrl + (baseUrl.includes('?') ? '&' : '?') + 'source=ubersicht-widget'
  const widgetName = cardType.replace(/_/g, '-')
  const consoleUrl = (apiEndpoint || 'http://localhost:8080').replace(/\/api$/, '')
  const shellCode = generateWidgetShell(widgetName, consoleUrl)

  return `/**
 * ${card.displayName} Widget
 * ${card.description}
 *
 * Generated by KubeStellar Console
 * Install: Move to ~/Library/Application Support/Übersicht/widgets/
 * Drag the ⋮⋮ handle to reposition. Position is saved automatically.
 */

${shellCode}

// Fetch agent token for auth, then fetch data (Übersicht's WebKit does not support fetch)
export const command = \`${generateWidgetCommand(consoleUrl, curlUrl)}\`;

export const refreshFrequency = ${refreshInterval};

${generateWidgetStyles()}

${generateCardRenderFunction(cardType, card.displayName)}
`
}

// Generate Übersicht widget code for stat blocks
export function generateStatWidget(
  statIds: string[],
  apiEndpoint: string,
  refreshInterval: number = 60000,
  layout: 'row' | 'grid' = 'row'
): string {
  const stats = statIds.map((id) => WIDGET_STATS[id]).filter(Boolean)
  if (stats.length === 0) {
    throw new Error('No valid stat IDs provided')
  }

  const base = apiEndpoint || 'http://localhost:8081'
  const endpoint = `${base}${stats[0].apiEndpoint}`
  const curlUrl = endpoint + (endpoint.includes('?') ? '&' : '?') + 'source=ubersicht-widget'

  return `/**
 * Stats Widget
 * Displays: ${stats.map((s) => s.displayName).join(', ')}
 *
 * Generated by KubeStellar Console
 */

// Fetch agent token for auth, then fetch data (Übersicht's WebKit does not support fetch)
export const command = \`${generateWidgetCommand(base, curlUrl)}\`;

export const refreshFrequency = ${refreshInterval};

${generateWidgetStyles()}

const WIDGET_NAME = 'stats-widget';
const openIssue = (errorMsg) => {
  const title = encodeURIComponent('[Widget] ' + WIDGET_NAME + ': ' + (errorMsg || 'unknown error'));
  const body = encodeURIComponent('**Widget:** ' + WIDGET_NAME + '\\n**Error:** ' + (errorMsg || 'unknown') + '\\n**Platform:** Übersicht (macOS)\\n\\n_Describe what you were doing when this happened:_\\n');
  run(\`open "https://github.com/kubestellar/console/issues/new?title=\${title}&body=\${body}&labels=kind/bug,area/widgets"\`);
};

const StatBlock = ({ value, label, color }) => (
  <div style={{...styles.statBlock, borderTop: \`3px solid \${color}\`}}>
    <span style={{...styles.statValue, color}}>{value}</span>
    <span style={styles.statLabel}>{label}</span>
  </div>
);

export const render = ({ output }) => {
  let data = null;
  let error = null;
  try {
    const trimmed = (output || '').trim();
    if (!trimmed || trimmed.includes('"error"')) {
      error = 'Load failed';
    } else {
      data = JSON.parse(trimmed);
    }
  } catch (e) {
    error = 'Parse error';
  }

  if (error) {
    return <div style={{...styles.column}}><div style={styles.row}><span style={{color: styles.colors.error}}>Error</span></div><div><button style={styles.issueBtn} onClick={() => openIssue(error)}>Report Issue</button></div></div>;
  }

  // Extract values from API responses.
  // Supports dotted paths ('a.b.c') AND bracket notation for array/numeric
  // index access ('items[0].foo.bar'). Without the bracket handling, a path
  // like 'items[0]' would be walked as src['items[0]'] which is always
  // undefined and silently returns 0, making stat widgets look broken.
  const getData = (path, src) => {
    try {
      const tokens = String(path)
        .replace(/\\[(\\w+)\\]/g, '.$1')
        .split('.')
        .filter(Boolean);
      let cur = src;
      for (const t of tokens) {
        if (cur == null) return 0;
        cur = cur[t];
      }
      return cur ?? 0;
    } catch {
      return 0;
    }
  };

  return (
    <div style={{...styles.${layout}, ${layout === 'grid' ? "gridTemplateColumns: 'repeat(2, 1fr)'" : ''}}}>
      ${stats
        .map((stat) => {
          return `<StatBlock
        value={getData('${stat.dataPath}', data)}
        label="${stat.displayName}"
        color="${stat.color}"
      />`
        })
        .join('\n      ')}
    </div>
  );
};
`
}

// Generate Übersicht widget code for a template
export function generateTemplateWidget(
  templateId: string,
  apiEndpoint: string,
  refreshInterval: number = 30000
): string {
  const template = WIDGET_TEMPLATES[templateId]
  if (!template) {
    throw new Error(`Unknown template ID: ${templateId}`)
  }

  // Collect all API endpoints from cards and stats
  const allEndpoints: string[] = []
  template.cards.forEach((cardType) => {
    const card = WIDGET_CARDS[cardType]
    if (card) {
      card.apiEndpoints.forEach((ep) => {
        if (!allEndpoints.includes(ep)) allEndpoints.push(ep)
      })
    }
  })
  template.stats?.forEach((statId) => {
    const stat = WIDGET_STATS[statId]
    if (stat && !allEndpoints.includes(stat.apiEndpoint)) allEndpoints.push(stat.apiEndpoint)
  })
  const validEndpoints = allEndpoints.filter((ep): ep is string => typeof ep === 'string' && ep.length > 0)
  const firstEndpoint = validEndpoints[0]
  if (!firstEndpoint) {
    throw new Error(`Template "${templateId}" has no resolvable data endpoint (no cards and no stat.apiEndpoint)`)
  }
  const base = apiEndpoint || 'http://localhost:8081'
  const curlUrl = `${base}${firstEndpoint}`

  const statComponents = (template.stats || []).map((id: string) => generateMiniStatComponent(id)).join('\n\n')

  return `/**
 * ${template.displayName} Template Widget
 * ${template.description}
 *
 * Generated by KubeStellar Console
 */

// Fetch agent token for auth, then fetch data (Übersicht's WebKit does not support fetch)
export const command = \`${generateWidgetCommand(base, curlUrl)}\`;

export const refreshFrequency = ${refreshInterval};

${generateWidgetStyles()}

const WIDGET_NAME = '${templateId.replace(/_/g, '-')}';
const openIssue = (errorMsg) => {
  const title = encodeURIComponent('[Widget] ' + WIDGET_NAME + ': ' + (errorMsg || 'unknown error'));
  const body = encodeURIComponent('**Widget:** ' + WIDGET_NAME + '\\n**Error:** ' + (errorMsg || 'unknown') + '\\n**Platform:** Übersicht (macOS)\\n\\n_Describe what you were doing when this happened:_\\n');
  run(\`open "https://github.com/kubestellar/console/issues/new?title=\${title}&body=\${body}&labels=kind/bug,area/widgets"\`);
};

${statComponents}

export const render = ({ output }) => {
  let data = null;
  let error = null;
  try {
    const trimmed = (output || '').trim();
    if (!trimmed || trimmed.includes('"error"')) {
      error = 'Load failed';
    } else {
      data = JSON.parse(trimmed);
    }
  } catch (e) {
    error = 'Parse error';
  }

  if (error) {
    return (
      <div style={styles.column}>
        <div style={styles.row}>
          <span style={{color: styles.colors.error}}>Error</span>
        </div>
        <div>
          <button style={styles.issueBtn} onClick={() => openIssue(error)}>
            Report Issue
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={styles.column}>
      <h3 style={{margin: '0 0 12px 0', fontSize: '16px'}}>${template.displayName}</h3>
      ${
        template.stats && template.stats.length > 0
          ? `<div style={styles.row}>
        ${template.stats.map((id: string) => `<${id.replace(/_/g, '')}Stat data={data} />`).join('\n        ')}
      </div>`
          : ''
      }
    </div>
  );
};
`
}

// Generate mini stat component for templates
export function generateMiniStatComponent(statId: string): string {
  const stat = WIDGET_STATS[statId]
  if (!stat) return ''

  const componentName = statId.replace(/_/g, '') + 'Stat'

  return `const ${componentName} = ({ data }) => {
  const value = (() => {
    try {
      return ${stat.dataPath.includes('reduce') || stat.dataPath.includes('filter') ? `(data?.${stat.dataPath.split('.')[0]} || []).${stat.dataPath.split('.').slice(1).join('.')}` : `data?.${stat.dataPath}`} || 0;
    } catch { return 0; }
  })();
  return (
    <div style={{...styles.statBlock, borderTop: '2px solid ${stat.color}'}}>
      <span style={{...styles.statValue, fontSize: '18px', color: '${stat.color}'}}>{value}${stat.format === 'percentage' ? '%' : ''}</span>
      <span style={{...styles.statLabel, fontSize: '9px'}}>${stat.displayName}</span>
    </div>
  );
};`
}
