import { useState, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Store, Search, Download, Tag, RefreshCw, Loader2, AlertCircle, Package,
  Check, Trash2, LayoutGrid, Puzzle, Palette, ExternalLink, Heart,
  HandHelping, List, Grid3X3, SortAsc, SortDesc, Sparkles } from 'lucide-react'
import { useMarketplace, MarketplaceItem, MarketplaceItemType } from '../../hooks/useMarketplace'
import { useSidebarConfig } from '../../hooks/useSidebarConfig'
import { useToast } from '../ui/Toast'
import { Input } from '../ui/Input'
import { DashboardHeader } from '../shared/DashboardHeader'
import { RotatingTip } from '../ui/RotatingTip'
import { CNCFProgressBanner } from './CNCFProgressBanner'
import { MarketplaceCard } from './MarketplaceCard'
import { AuthorBadge } from './AuthorBadge'
import { DifficultyBadge } from './DifficultyBadge'
import { NAV_AFTER_ANIMATION_MS } from '../../lib/constants/network'
import { suggestIconSync } from '../../lib/iconSuggester'
import { useTranslation } from 'react-i18next'
import type { CSSProperties } from 'react'