/**
 * Netlify Function: Compliance ERM Risk Register Risks
 *
 * Returns static demo risk register entries for the enterprise risk register dashboard
 * so production renders the same sample content as development without the Go backend.
 */
import { wrapIdentityDemoResponse } from "./_shared/identity-demo-request";

export default async (req: Request) => {
  return wrapIdentityDemoResponse(req, [
    { id: "RSK-001", name: "Cloud provider outage", description: "Single cloud provider failure causes widespread service disruption across production clusters.", category: "Technology", likelihood: 3, impact: 5, score: 15, owner: "CTO", status: "Open", last_review: "2025-01-10T00:00:00Z", next_review: "2025-04-10T00:00:00Z", mitigation_plan: "Implement multi-cloud strategy with automatic failover. Deploy across AWS, GCP, and Azure with cross-region replication.", controls: ["Multi-region deployment", "Auto-failover", "DR playbook"], created_at: "2024-06-15T00:00:00Z" },
    { id: "RSK-002", name: "Data breach via supply chain", description: "Compromised third-party dependency introduces vulnerability enabling data exfiltration.", category: "Technology", likelihood: 4, impact: 5, score: 20, owner: "CISO", status: "Mitigating", last_review: "2025-01-08T00:00:00Z", next_review: "2025-02-08T00:00:00Z", mitigation_plan: "SBOM scanning on all images, Sigstore verification required for production. SLSA L3 for critical builds.", controls: ["SBOM scanning", "Sigstore verification", "SLSA L3", "Dependency review"], created_at: "2024-03-10T00:00:00Z" },
    { id: "RSK-003", name: "Regulatory non-compliance fine", description: "Failure to meet SOC 2 or PCI-DSS requirements leading to regulatory penalties.", category: "Compliance", likelihood: 2, impact: 5, score: 10, owner: "CCO", status: "Open", last_review: "2025-01-05T00:00:00Z", next_review: "2025-03-05T00:00:00Z", mitigation_plan: "Continuous compliance monitoring with automated evidence collection. Quarterly audits.", controls: ["Compliance dashboard", "Automated evidence", "Quarterly audits"], created_at: "2024-01-20T00:00:00Z" },
    { id: "RSK-004", name: "Key personnel departure", description: "Loss of critical engineering or security staff creates knowledge gaps.", category: "Operational", likelihood: 3, impact: 4, score: 12, owner: "CHRO", status: "Accepted", last_review: "2025-01-12T00:00:00Z", next_review: "2025-04-12T00:00:00Z", mitigation_plan: "Cross-training program, comprehensive documentation, competitive retention packages.", controls: ["Knowledge base", "Cross-training", "Retention packages"], created_at: "2024-05-01T00:00:00Z" },
    { id: "RSK-005", name: "Market share erosion", description: "Competitors launching similar platforms reduces customer acquisition and retention.", category: "Strategic", likelihood: 3, impact: 3, score: 9, owner: "CSO", status: "Open", last_review: "2025-01-06T00:00:00Z", next_review: "2025-04-06T00:00:00Z", mitigation_plan: "Accelerate feature development, enhance enterprise integrations, strengthen community.", controls: ["Competitive analysis", "Feature roadmap", "Community growth"], created_at: "2024-07-15T00:00:00Z" },
    { id: "RSK-006", name: "Currency exchange volatility", description: "Unfavorable exchange rates impacting international revenue and costs.", category: "Financial", likelihood: 4, impact: 3, score: 12, owner: "CFO", status: "Mitigating", last_review: "2025-01-11T00:00:00Z", next_review: "2025-03-11T00:00:00Z", mitigation_plan: "Hedging strategy for major currency pairs, invoice in local currencies where possible.", controls: ["FX hedging", "Multi-currency billing", "Treasury management"], created_at: "2024-09-01T00:00:00Z" },
    { id: "RSK-007", name: "Negative media coverage", description: "Public relations incident damages brand and customer trust.", category: "Reputational", likelihood: 2, impact: 4, score: 8, owner: "CMO", status: "Open", last_review: "2025-01-09T00:00:00Z", next_review: "2025-04-09T00:00:00Z", mitigation_plan: "Crisis communication plan, media monitoring, proactive transparency reports.", controls: ["Crisis comms plan", "Media monitoring", "PR team"], created_at: "2024-04-20T00:00:00Z" },
    { id: "RSK-008", name: "Kubernetes cluster compromise", description: "Unauthorized access to production clusters enabling lateral movement.", category: "Technology", likelihood: 3, impact: 5, score: 15, owner: "CISO", status: "Mitigating", last_review: "2025-01-13T00:00:00Z", next_review: "2025-02-13T00:00:00Z", mitigation_plan: "Zero-trust architecture, RBAC audit, network policies, runtime security with Falco.", controls: ["RBAC audit", "Network policies", "Falco alerts", "Pod security standards"], created_at: "2024-02-15T00:00:00Z" },
    { id: "RSK-009", name: "Third-party vendor bankruptcy", description: "Critical vendor going out of business disrupts service delivery.", category: "Operational", likelihood: 2, impact: 3, score: 6, owner: "CPO", status: "Accepted", last_review: "2025-01-07T00:00:00Z", next_review: "2025-07-07T00:00:00Z", mitigation_plan: "Vendor diversity strategy, escrow agreements for source code, contract exit clauses.", controls: ["Vendor diversity", "Code escrow", "Exit clauses"], created_at: "2024-08-10T00:00:00Z" },
    { id: "RSK-010", name: "Insider threat data exfiltration", description: "Malicious insider copies sensitive data for unauthorized purposes.", category: "Technology", likelihood: 2, impact: 5, score: 10, owner: "CISO", status: "Open", last_review: "2025-01-14T00:00:00Z", next_review: "2025-03-14T00:00:00Z", mitigation_plan: "DLP policies, SIEM monitoring, least-privilege access, session recording.", controls: ["DLP", "SIEM", "Least privilege", "Session recording"], created_at: "2024-06-01T00:00:00Z" },
    { id: "RSK-016", name: "GDPR violation", description: "Non-compliance with EU data protection regulation resulting in fines up to 4% of revenue.", category: "Compliance", likelihood: 2, impact: 5, score: 10, owner: "DPO", status: "Mitigating", last_review: "2025-01-11T00:00:00Z", next_review: "2025-02-11T00:00:00Z", mitigation_plan: "Data residency controls, consent management, DPIA for all new processing, breach notification workflow.", controls: ["Data residency", "Consent management", "DPIA", "Breach notification"], created_at: "2024-01-05T00:00:00Z" },
    { id: "RSK-017", name: "Critical CVE in base images", description: "Zero-day or critical vulnerability in container base images deployed across fleet.", category: "Technology", likelihood: 4, impact: 4, score: 16, owner: "CISO", status: "Mitigating", last_review: "2025-01-14T00:00:00Z", next_review: "2025-02-14T00:00:00Z", mitigation_plan: "Automated image scanning in CI/CD, distroless base images, rapid patching SLA of 24h for critical CVEs.", controls: ["Image scanning", "Distroless images", "Patch SLA", "Admission controllers"], created_at: "2024-04-01T00:00:00Z" },
  ]);
};
