/* Split from useStellar.test.tsx for focused test modules. */
import "./useStellar.test.usestellar-fallback-outside-provider.tsx"
import "./useStellar.test.stellarprovider-initial-state.tsx"
import "./useStellar.test.stellarprovider-batch-scheduling.tsx"
import "./useStellar.test.stellarprovider-sse-events.tsx"
import "./useStellar.test.stellarprovider-actions.tsx"
import "./useStellar.test.stellarprovider-task-management.tsx"
import "./useStellar.test.stellarprovider-watch-management.tsx"
import "./useStellar.test.stellarprovider-startsolve.tsx"
import "./useStellar.test.stellarprovider-dismissallnotifications.tsx"
import "./useStellar.test.stellarprovider-unreadcount.tsx"
import "./useStellar.test.stellarprovider-sse-lifecycle-14220.tsx"
import "./useStellar.test.stellarprovider-malformed-sse-data.tsx"
