{{- if and .Values.kubeconfig.content (not .Values.kubeconfig.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubestellar-console.kubeconfigSecretName" . }}
  labels:
    {{- include "kubestellar-console.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.kubeconfig.existingSecretKey }}: |-
{{ .Values.kubeconfig.content | nindent 4 }}
{{- end }}
