import type { MultiClusterInsight } from '../../types/insights'
import {
  DEMO_OFFSET_5M_MS,
  DEMO_OFFSET_10M_MS,
  DEMO_OFFSET_15M_MS,
  FULL_PROGRESS,
  PARTIAL_PROGRESS,
  ROLLOUT_STATUS_COMPLETE,
  ROLLOUT_STATUS_FAILED,
  ROLLOUT_STATUS_IN_PROGRESS,
} from './constants'

export function getDemoInsights(): MultiClusterInsight[] {
  const demoTime = new Date()
  const fiveMinAgo = new Date(demoTime.getTime() - DEMO_OFFSET_5M_MS).toISOString()
  const tenMinAgo = new Date(demoTime.getTime() - DEMO_OFFSET_10M_MS).toISOString()
  const fifteenMinAgo = new Date(demoTime.getTime() - DEMO_OFFSET_15M_MS).toISOString()

  return [
    {
      id: 'demo-event-correlation-1',
      category: 'event-correlation',
      source: 'heuristic',
      severity: 'critical',
      title: '3 clusters had simultaneous warnings',
      description: '18 warning events across eks-prod-us-east-1, gke-staging, openshift-prod within a 5-minute window. Common reasons: BackOff, FailedScheduling.',
      affectedClusters: ['eks-prod-us-east-1', 'gke-staging', 'openshift-prod'],
      relatedResources: ['api-server', 'metrics-collector'],
      detectedAt: fiveMinAgo,
      remediation: 'Check shared infrastructure (DNS, load balancer, or shared storage) that all three clusters depend on. The simultaneous timing strongly suggests a common upstream dependency failure.',
    },
    {
      id: 'demo-resource-imbalance-cpu',
      category: 'resource-imbalance',
      source: 'ai',
      severity: 'warning',
      confidence: 82,
      provider: 'claude',
      title: 'CPU imbalance across fleet (avg 54%)',
      description: 'eks-prod-us-east-1 is significantly overloaded at 87% CPU while aks-dev-westeu sits at only 22%. This 65-point spread indicates workloads are not evenly distributed across the fleet.',
      affectedClusters: ['eks-prod-us-east-1', 'aks-dev-westeu'],
      detectedAt: fiveMinAgo,
      remediation: 'Consider migrating 2-3 non-critical workloads from eks-prod-us-east-1 to aks-dev-westeu. Alternatively, enable HPA on the top CPU consumers in eks-prod to allow autoscaling.',
      metrics: {
        'eks-prod-us-east-1': 87,
        'gke-staging': 55,
        'openshift-prod': 62,
        'aks-dev-westeu': 22,
        'vllm-gpu-cluster': 45,
      },
    },
    {
      id: 'demo-restart-app-bug',
      category: 'restart-correlation',
      source: 'heuristic',
      severity: 'warning',
      title: 'default/api-server restarting across 3 clusters (likely app bug)',
      description: 'default/api-server has 26 total restarts across eks-prod-us-east-1, gke-staging, openshift-prod. Same workload failing everywhere suggests an application-level issue.',
      affectedClusters: ['eks-prod-us-east-1', 'gke-staging', 'openshift-prod'],
      relatedResources: ['default/api-server'],
      detectedAt: tenMinAgo,
      remediation: 'Check api-server logs for OOMKilled or panic traces. Since the same workload fails across all clusters, this is almost certainly an application bug — not infrastructure. Roll back to the previous image if this started after a recent deployment.',
    },
    {
      id: 'demo-restart-infra-issue',
      category: 'restart-correlation',
      source: 'heuristic',
      severity: 'critical',
      title: '4 workloads restarting in vllm-gpu-cluster (likely infra issue)',
      description: 'Multiple different workloads (default/metrics-collector, default/cache-redis, default/gpu-scheduler, default/log-agent) are restarting in vllm-gpu-cluster. This pattern suggests an infrastructure problem rather than an application bug.',
      affectedClusters: ['vllm-gpu-cluster'],
      relatedResources: ['default/metrics-collector', 'default/cache-redis', 'default/gpu-scheduler', 'default/log-agent'],
      detectedAt: tenMinAgo,
    },
    {
      id: 'demo-cascade-1',
      category: 'cascade-impact',
      source: 'ai',
      severity: 'critical',
      confidence: 91,
      provider: 'claude',
      title: 'Possible cascade across 3 clusters',
      description: 'A shared ConfigMap mount failure in openshift-prod propagated to dependent services in eks-prod-us-east-1 and gke-staging. The cascade pattern matches a centralized config distribution failure.',
      affectedClusters: ['openshift-prod', 'eks-prod-us-east-1', 'gke-staging'],
      detectedAt: fifteenMinAgo,
      remediation: 'The root cause is the FailedMount in openshift-prod/config-service. Check if the backing Secret or ConfigMap was recently modified or deleted. Restoring it should resolve the downstream Unhealthy and CrashLoopBackOff issues within minutes.',
      chain: [
        { cluster: 'openshift-prod', resource: 'config-service', event: 'FailedMount', timestamp: fifteenMinAgo, severity: 'warning' },
        { cluster: 'eks-prod-us-east-1', resource: 'api-gateway', event: 'Unhealthy', timestamp: tenMinAgo, severity: 'warning' },
        { cluster: 'gke-staging', resource: 'frontend', event: 'CrashLoopBackOff', timestamp: fiveMinAgo, severity: 'critical' },
      ],
    },
    {
      id: 'demo-config-drift-1',
      category: 'config-drift',
      source: 'heuristic',
      severity: 'warning',
      title: 'Config drift in default/api-server',
      description: 'default/api-server has 3 different images and 2 different replica counts across 4 clusters.',
      affectedClusters: ['eks-prod-us-east-1', 'gke-staging', 'openshift-prod', 'aks-dev-westeu'],
      relatedResources: ['default/api-server'],
      detectedAt: fiveMinAgo,
      remediation: 'Standardize on the newest stable image across all clusters. Use a KubeStellar BindingPolicy to enforce consistent image versions and replica counts fleet-wide.',
    },
    {
      id: 'demo-cluster-delta-1',
      category: 'cluster-delta',
      source: 'heuristic',
      severity: 'warning',
      title: 'default/api-server differs across 2 clusters',
      description: 'Found 3 differences: Image Version, Replica Count, Status.',
      affectedClusters: ['eks-prod-us-east-1', 'gke-staging'],
      relatedResources: ['default/api-server'],
      detectedAt: fiveMinAgo,
      deltas: [
        { dimension: 'Image Version', clusterA: { name: 'eks-prod-us-east-1', value: 'api-server:v2.1.0' }, clusterB: { name: 'gke-staging', value: 'api-server:v2.0.3' }, significance: 'high' },
        { dimension: 'Replica Count', clusterA: { name: 'eks-prod-us-east-1', value: 5 }, clusterB: { name: 'gke-staging', value: 3 }, significance: 'medium' },
        { dimension: 'Status', clusterA: { name: 'eks-prod-us-east-1', value: 'running' }, clusterB: { name: 'gke-staging', value: 'deploying' }, significance: 'medium' },
      ],
    },
    {
      id: 'demo-rollout-1',
      category: 'rollout-tracker',
      source: 'heuristic',
      severity: 'warning',
      title: 'Rollout in progress: default/api-server',
      description: '3/5 clusters on api-server:v2.1.0. 1 pending, 1 failed.',
      affectedClusters: ['eks-prod-us-east-1', 'gke-staging', 'openshift-prod', 'aks-dev-westeu', 'vllm-gpu-cluster'],
      relatedResources: ['default/api-server'],
      detectedAt: fiveMinAgo,
      metrics: {
        completed: 3,
        pending: 1,
        failed: 1,
        total: 5,
        'eks-prod-us-east-1_progress': FULL_PROGRESS,
        'eks-prod-us-east-1_status': ROLLOUT_STATUS_COMPLETE,
        'gke-staging_progress': FULL_PROGRESS,
        'gke-staging_status': ROLLOUT_STATUS_COMPLETE,
        'openshift-prod_progress': FULL_PROGRESS,
        'openshift-prod_status': ROLLOUT_STATUS_COMPLETE,
        'aks-dev-westeu_progress': PARTIAL_PROGRESS,
        'aks-dev-westeu_status': ROLLOUT_STATUS_IN_PROGRESS,
        'vllm-gpu-cluster_progress': 0,
        'vllm-gpu-cluster_status': ROLLOUT_STATUS_FAILED,
      },
    },
  ]
}
