#!/bin/bash
# Generate a markdown weekly summary from the last 7 nightly test results.
#
# Usage:
#   ./scripts/nightly-weekly-summary.sh [results-dir]
#
# Output:
#   Writes markdown to stdout, suitable for posting in a GitHub issue comment
#   or saving as a report file.

set -euo pipefail

RESULTS_DIR="${1:-test-results/nightly}"
WINDOW=7

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required" >&2
  exit 1
fi

# Use the health dashboard generator as the data source
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HEALTH_JSON=$("$SCRIPT_DIR/nightly-health-dashboard.sh" "$RESULTS_DIR" "$WINDOW")

# Extract top-level fields
GENERATED=$(echo "$HEALTH_JSON" | jq -r '.generatedAt')
WINDOW_SIZE=$(echo "$HEALTH_JSON" | jq -r '.windowSize')
HEALTH_SCORE=$(echo "$HEALTH_JSON" | jq -r '.health.score')
PASS_TREND=$(echo "$HEALTH_JSON" | jq -r '.health.passRateTrend')
FLAKY_COUNT=$(echo "$HEALTH_JSON" | jq -r '.health.flakyCount')
TOTAL_SUITES=$(echo "$HEALTH_JSON" | jq -r '.health.totalSuites')
AVG_STABILITY=$(echo "$HEALTH_JSON" | jq -r '.health.avgStabilityPct')

LATEST_DATE=$(echo "$HEALTH_JSON" | jq -r '.latest.date')
LATEST_PASSED=$(echo "$HEALTH_JSON" | jq -r '.latest.passed')
LATEST_FAILED=$(echo "$HEALTH_JSON" | jq -r '.latest.failed')
LATEST_TOTAL=$(echo "$HEALTH_JSON" | jq -r '.latest.total')
LATEST_RATE=$(echo "$HEALTH_JSON" | jq -r '.latest.passRate')

# Health emoji
if [ "$HEALTH_SCORE" -ge 90 ]; then
  HEALTH_EMOJI=":green_circle:"
elif [ "$HEALTH_SCORE" -ge 70 ]; then
  HEALTH_EMOJI=":yellow_circle:"
else
  HEALTH_EMOJI=":red_circle:"
fi

# Trend emoji
case "$PASS_TREND" in
  improving) TREND_EMOJI=":chart_with_upwards_trend:" ;;
  declining) TREND_EMOJI=":chart_with_downwards_trend:" ;;
  *)         TREND_EMOJI=":left_right_arrow:" ;;
esac

cat <<EOF
## :clipboard: Nightly Test Weekly Summary

${HEALTH_EMOJI} **Health Score: ${HEALTH_SCORE}/100** | ${TREND_EMOJI} Pass rate: **${PASS_TREND}** | Window: last ${WINDOW_SIZE} runs

> Generated: ${GENERATED}

---

### Latest Run (${LATEST_DATE})

| Metric | Value |
|--------|-------|
| Total suites | ${LATEST_TOTAL} |
| Passed | ${LATEST_PASSED} |
| Failed | ${LATEST_FAILED} |
| Pass rate | ${LATEST_RATE}% |

### Overall Health

| Metric | Value |
|--------|-------|
| Health score | ${HEALTH_SCORE}/100 |
| Average stability | ${AVG_STABILITY}% |
| Flaky suites | ${FLAKY_COUNT} |
| Total suites tracked | ${TOTAL_SUITES} |
| Pass rate trend | ${PASS_TREND} |

### Pass Rate Trend

| Date | Passed | Failed | Total | Rate |
|------|--------|--------|-------|------|
EOF

echo "$HEALTH_JSON" | jq -r '.trend[] | "| \(.date | split("T")[0]) | \(.passed) | \(.failed) | \(.total) | \(.passRate)% |"'

echo ""

# Duration trend
echo "### Duration Trend"
echo ""
echo "| Date | Avg Suite (s) | Total Run (s) |"
echo "|------|---------------|---------------|"
echo "$HEALTH_JSON" | jq -r '.trend[] | "| \(.date | split("T")[0]) | \(.avgDurationSec) | \(.totalDurationSec) |"'
echo ""

# Flaky suites
if [ "$FLAKY_COUNT" -gt 0 ]; then
  echo "### :warning: Flaky Suites"
  echo ""
  echo "These suites alternated between pass and fail **2+ times** in the last ${WINDOW_SIZE} runs:"
  echo ""
  echo "| Suite | Flips | Pass | Fail | Stability |"
  echo "|-------|-------|------|------|-----------|"
  echo "$HEALTH_JSON" | jq -r '.suites[] | select(.isFlaky == true) | "| `\(.suite)` | \(.flips) | \(.passCount) | \(.failCount) | \(.stabilityPct)% |"'
  echo ""
fi

# Consistently failing suites
FAIL_SUITES=$(echo "$HEALTH_JSON" | jq '[.suites[] | select(.latestStatus == "fail" and .isFlaky == false)] | length')
if [ "$FAIL_SUITES" -gt 0 ]; then
  echo "### :x: Consistently Failing"
  echo ""
  echo "| Suite | Fail Count | Stability | Duration Trend |"
  echo "|-------|------------|-----------|----------------|"
  echo "$HEALTH_JSON" | jq -r '.suites[] | select(.latestStatus == "fail" and .isFlaky == false) | "| `\(.suite)` | \(.failCount)/\(.presentRuns) | \(.stabilityPct)% | \(.durationTrend) |"'
  echo ""
fi

# Slowest suites
echo "### :hourglass: Slowest Suites (by avg duration)"
echo ""
echo "| Suite | Avg (s) | Min (s) | Max (s) | Trend |"
echo "|-------|---------|---------|---------|-------|"
echo "$HEALTH_JSON" | jq -r '[.suites[] | select(.durationAvgSec > 0)] | sort_by(-.durationAvgSec) | .[:10][] | "| `\(.suite)` | \(.durationAvgSec) | \(.durationMinSec) | \(.durationMaxSec) | \(.durationTrend) |"'
echo ""

echo "---"
echo "_Generated by \`scripts/nightly-weekly-summary.sh\`. Data from \`scripts/nightly-health-dashboard.sh\`._"
