#!/usr/bin/env bash
# update-widgets.sh — Patch deployed Übersicht widgets with the current auth pattern.
#
# Called by startup-oauth.sh after the backend starts. Ensures all widget
# `export const command` lines use the agent-token-with-cache pattern so
# users never need to manually re-export widgets after auth changes.
#
# Safe to run repeatedly — idempotent. Only touches KubeStellar Console
# widgets (identified by "Generated by KubeStellar Console" in the file).

set -euo pipefail

WIDGET_DIR="${HOME}/Library/Application Support/Übersicht/widgets"
TOKEN_CACHE="/tmp/.kc-widget-token"
# Backend port — startup-oauth.sh runs the backend on BACKEND_PORT (default 8081)
BACKEND_PORT="${BACKEND_PORT:-8081}"
TOKEN_URL="http://localhost:${BACKEND_PORT}/api/agent/token?source=ubersicht-widget"

if [ ! -d "$WIDGET_DIR" ]; then
  exit 0
fi

UPDATED=0
SKIPPED=0

for widget in "$WIDGET_DIR"/*.widget.jsx; do
  [ -f "$widget" ] || continue
  name=$(basename "$widget")

  # Only touch KubeStellar Console widgets
  if ! grep -q "Generated by KubeStellar Console" "$widget" 2>/dev/null; then
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  # Already has the current pattern (cached token + auto-retry)
  if grep -q "kc-widget-token" "$widget" 2>/dev/null; then
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  /usr/bin/python3 - "$widget" "$TOKEN_CACHE" "$TOKEN_URL" << 'PYEOF'
import re, sys

widget_path = sys.argv[1]
token_cache = sys.argv[2]
token_url = sys.argv[3]

with open(widget_path, 'r') as f:
    content = f.read()

m = re.search(r"^export const command = `(.*?)`;$", content, re.MULTILINE | re.DOTALL)
if not m:
    sys.exit(0)

old_cmd = m.group(1)

# Extract the data URL — try quoted then unquoted
url_m = re.search(r"'(http://localhost:808[01]/api/[^']+)'", old_cmd)
if not url_m:
    url_m = re.search(r"(http://localhost:808[01]/api/\S+)", old_cmd)
if not url_m:
    sys.exit(0)

curl_url = url_m.group(1)

# Grep-based pattern avoids awk/sed — those use ${} which JS backticks interpolate
new_cmd = (
    f"TOKEN=$(cat {token_cache} 2>/dev/null); "
    f"OUT=$(/usr/bin/curl -s --connect-timeout 5 "
    f"-H \"Authorization: Bearer $TOKEN\" '{curl_url}' 2>/dev/null); "
    f"if echo \"$OUT\" | grep -q \"Missing authorization\" || [ -z \"$TOKEN\" ]; then "
    f"TOKEN=$(/usr/bin/curl -s --connect-timeout 3 '{token_url}' 2>/dev/null "
    f"| /usr/bin/python3 -c \"import sys,json; print(json.load(sys.stdin).get('token',''))\" 2>/dev/null); "
    f"echo \"$TOKEN\" > {token_cache}; "
    f"/usr/bin/curl -s --connect-timeout 5 "
    f"-H \"Authorization: Bearer $TOKEN\" '{curl_url}' 2>/dev/null "
    f"|| echo '{{\"error\":\"Load failed\"}}'; "
    f"else echo \"$OUT\"; fi"
)

new_line = f"export const command = `{new_cmd}`;"
new_content = re.sub(r"^export const command = `.*?`;$", new_line, content, count=1, flags=re.MULTILINE | re.DOTALL)

with open(widget_path, 'w') as f:
    f.write(new_content)

print(f"  Updated: {widget_path.split('/')[-1]}")
PYEOF

  UPDATED=$((UPDATED + 1))
done

if [ "$UPDATED" -gt 0 ]; then
  echo "[Widgets] Updated $UPDATED widget(s) with current auth pattern ($SKIPPED skipped)"
else
  echo "[Widgets] All $SKIPPED widget(s) already current"
fi
