package reports

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/kubestellar/console/pkg/compliance/frameworks"
)

// pdfDoc is a minimal PDF writer that produces valid PDF 1.4 documents
// without external dependencies. It builds the cross-reference table
// and page tree required by the PDF specification.
type pdfDoc struct {
	buf     bytes.Buffer
	offsets []int // byte offset of each object
}

const (
	pdfFontSize      = 10
	pdfTitleFontSize = 18
	pdfHeaderSize    = 14
	pdfLineHeight    = 14
	pdfPageWidth     = 612 // US Letter
	pdfPageHeight    = 792
	pdfMargin        = 50
)

// GeneratePDF produces a PDF compliance report from an evaluation result.
// It uses a dependency-free PDF writer to avoid external library requirements.
func GeneratePDF(fw *frameworks.Framework, result *frameworks.EvaluationResult, userName string) ([]byte, error) {
	doc := &pdfDoc{}
	lines := buildReportLines(fw, result, userName)
	pages := paginateLines(lines, pdfPageHeight-2*pdfMargin, pdfLineHeight)

	doc.writeHeader()

	// Object 1: Catalog
	catalogObj := doc.startObject()
	doc.buf.WriteString(fmt.Sprintf("%d 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n", catalogObj))

	// Object 2: Pages (placeholder, updated later)
	pagesObj := doc.startObject()
	_ = pagesObj

	// Object 3: Font
	fontObj := doc.startObject()
	doc.buf.WriteString(fmt.Sprintf("%d 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n", fontObj))

	fontBoldObj := doc.startObject()
	doc.buf.WriteString(fmt.Sprintf("%d 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n", fontBoldObj))

	// Build page objects
	pageObjNums := make([]int, 0, len(pages))
	contentObjNums := make([]int, 0, len(pages))

	for _, page := range pages {
		// Content stream
		contentObj := doc.startObject()
		stream := buildPageStream(page, fontObj, fontBoldObj)
		doc.buf.WriteString(fmt.Sprintf("%d 0 obj\n<< /Length %d >>\nstream\n%s\nendstream\nendobj\n",
			contentObj, len(stream), stream))
		contentObjNums = append(contentObjNums, contentObj)

		// Page object
		pageObj := doc.startObject()
		doc.buf.WriteString(fmt.Sprintf(
			"%d 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 %d %d] /Contents %d 0 R /Resources << /Font << /F1 %d 0 R /F2 %d 0 R >> >> >>\nendobj\n",
			pageObj, pdfPageWidth, pdfPageHeight, contentObj, fontObj, fontBoldObj))
		pageObjNums = append(pageObjNums, pageObj)
	}

	// Rewrite pages object
	kids := make([]string, len(pageObjNums))
	for i, n := range pageObjNums {
		kids[i] = fmt.Sprintf("%d 0 R", n)
	}
	pagesOff := doc.offsets[1] // object 2 offset
	_ = pagesOff
	// We need to rebuild the pages entry
	doc.rewritePagesObject(pageObjNums)

	return doc.finalize()
}

type reportLine struct {
	text   string
	bold   bool
	size   float64
	indent float64
	spacer float64 // extra space before this line
}

func buildReportLines(fw *frameworks.Framework, result *frameworks.EvaluationResult, userName string) []reportLine {
	lines := []reportLine{
		{text: "COMPLIANCE REPORT", bold: true, size: pdfTitleFontSize, spacer: 10},
		{text: fw.Name + " " + fw.Version, bold: true, size: pdfHeaderSize, spacer: 8},
		{spacer: 6},
		{text: fmt.Sprintf("Cluster: %s", result.ClusterName), size: pdfFontSize},
		{text: fmt.Sprintf("Generated: %s", time.Now().UTC().Format("2006-01-02 15:04:05 UTC")), size: pdfFontSize},
		{text: fmt.Sprintf("Generated by: %s", userName), size: pdfFontSize},
		{spacer: 12},
		{text: "EXECUTIVE SUMMARY", bold: true, size: pdfHeaderSize, spacer: 4},
		{spacer: 4},
		{text: fmt.Sprintf("Overall Score: %d%%", result.Score), bold: true, size: 12},
		{text: fmt.Sprintf("Total Checks: %d  |  Passed: %d  |  Failed: %d  |  Partial: %d  |  Errors: %d",
			result.TotalChecks, result.Passed, result.Failed, result.Partial, result.Errors), size: pdfFontSize},
		{spacer: 12},
		{text: "DETAILED FINDINGS", bold: true, size: pdfHeaderSize, spacer: 4},
	}

	for _, ctrl := range result.Controls {
		lines = append(lines, reportLine{spacer: 8})
		lines = append(lines, reportLine{
			text: fmt.Sprintf("[%s] %s — %s (Severity: %s)",
				strings.ToUpper(string(ctrl.Status)), ctrl.ControlID, ctrl.Title, ctrl.Severity),
			bold: true, size: pdfFontSize,
		})

		for _, check := range ctrl.Checks {
			status := strings.ToUpper(string(check.Status))
			line := fmt.Sprintf("[%s] %s", status, check.Name)
			if check.Evidence != "" {
				line += " — " + check.Evidence
			}
			if check.Message != "" {
				line += " — " + check.Message
			}
			lines = append(lines, reportLine{text: line, size: 9, indent: 20})
		}

		if ctrl.Remediation != "" {
			lines = append(lines, reportLine{
				text:   "Remediation: " + ctrl.Remediation,
				size:   9,
				indent: 20,
			})
		}
	}

	return lines
}

func paginateLines(lines []reportLine, usableHeight float64, defaultLineHeight float64) [][]reportLine {
	var pages [][]reportLine
	var current []reportLine
	y := 0.0

	for _, line := range lines {
		lh := defaultLineHeight
		if line.size > pdfFontSize {
			lh = line.size * 1.5
		}
		needed := line.spacer + lh

		if y+needed > usableHeight && len(current) > 0 {
			pages = append(pages, current)
			current = nil
			y = 0
		}
		current = append(current, line)
		y += needed
	}
	if len(current) > 0 {
		pages = append(pages, current)
	}
	return pages
}

func buildPageStream(lines []reportLine, _, _ int) string {
	var sb strings.Builder
	sb.WriteString("BT\n")

	y := float64(pdfPageHeight - pdfMargin)

	for _, line := range lines {
		y -= line.spacer

		lh := float64(pdfLineHeight)
		if line.size > pdfFontSize {
			lh = line.size * 1.5
		}
		y -= lh

		if line.text == "" {
			continue
		}

		x := float64(pdfMargin) + line.indent
		// Font resource names must match /F1 (regular) and /F2 (bold) as
		// declared in the page's /Resources /Font dictionary. Using the
		// object-number directly (e.g. /F3) would leave the font unresolved
		// and produce blank text in compliant PDF readers.
		fontName := "F1"
		if line.bold {
			fontName = "F2"
		}
		size := line.size
		if size == 0 {
			size = pdfFontSize
		}

		sb.WriteString(fmt.Sprintf("/%s %g Tf\n", fontName, size))
		sb.WriteString(fmt.Sprintf("%g %g Td\n", x, y))
		sb.WriteString(fmt.Sprintf("(%s) Tj\n", escapePDF(line.text)))
		// Reset position for next absolute placement
		sb.WriteString(fmt.Sprintf("%g %g Td\n", -x, -y))
	}

	sb.WriteString("ET\n")
	return sb.String()
}

func escapePDF(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `(`, `\(`)
	s = strings.ReplaceAll(s, `)`, `\)`)
	return s
}

func (d *pdfDoc) writeHeader() {
	d.buf.WriteString("%PDF-1.4\n")
}

func (d *pdfDoc) startObject() int {
	d.offsets = append(d.offsets, d.buf.Len())
	return len(d.offsets)
}

func (d *pdfDoc) rewritePagesObject(pageObjNums []int) {
	// The pages object is object 2. We stored a placeholder.
	// In our simple implementation, we write it now.
	kids := make([]string, len(pageObjNums))
	for i, n := range pageObjNums {
		kids[i] = fmt.Sprintf("%d 0 R", n)
	}
	pagesContent := fmt.Sprintf("2 0 obj\n<< /Type /Pages /Kids [%s] /Count %d >>\nendobj\n",
		strings.Join(kids, " "), len(pageObjNums))

	// Replace the placeholder at offsets[1]
	before := d.buf.Bytes()[:d.offsets[1]]
	after := d.buf.Bytes()[d.offsets[1]:]

	var newBuf bytes.Buffer
	newBuf.Write(before)
	pagesOff := newBuf.Len()
	newBuf.WriteString(pagesContent)

	// Adjust offsets for objects after the pages object
	sizeDiff := len(pagesContent) // we inserted, not replaced

	// Find where the next object starts (offset[2] if exists)
	var restStart int
	if len(d.offsets) > 2 {
		restStart = d.offsets[2]
	} else {
		restStart = len(d.buf.Bytes())
	}
	newBuf.Write(after[restStart-d.offsets[1]:])

	// Update offsets
	d.offsets[1] = pagesOff
	for i := 2; i < len(d.offsets); i++ {
		d.offsets[i] += sizeDiff
	}

	d.buf = newBuf
}

func (d *pdfDoc) finalize() ([]byte, error) {
	// Write xref table
	xrefOff := d.buf.Len()
	d.buf.WriteString("xref\n")
	d.buf.WriteString(fmt.Sprintf("0 %d\n", len(d.offsets)+1))
	d.buf.WriteString("0000000000 65535 f \n")
	for _, off := range d.offsets {
		d.buf.WriteString(fmt.Sprintf("%010d 00000 n \n", off))
	}

	// Trailer
	d.buf.WriteString(fmt.Sprintf("trailer\n<< /Size %d /Root 1 0 R >>\n", len(d.offsets)+1))
	d.buf.WriteString(fmt.Sprintf("startxref\n%d\n%%%%EOF\n", xrefOff))

	return d.buf.Bytes(), nil
}
