/* Split from ModalRuntime-coverage.test.tsx for focused test modules. */
import "./ModalRuntime-coverage.test.modalruntime-rendering.tsx"
import "./ModalRuntime-coverage.test.modalruntime-section-types.tsx"
import "./ModalRuntime-coverage.test.modalruntime-header-sections.tsx"
import "./ModalRuntime-coverage.test.modalruntime-actions.tsx"
import "./ModalRuntime-coverage.test.modalruntime-custom-renderers.tsx"
import "./ModalRuntime-coverage.test.modalruntime-footer.tsx"
import "./ModalRuntime-coverage.test.modalruntime-keyboard-config.tsx"
import "./ModalRuntime-coverage.test.modalruntime-table-section-edge-cases.tsx"
import "./ModalRuntime-coverage.test.modalruntime-key-value-with-linkto.tsx"
import "./ModalRuntime-coverage.test.modalruntime-badges-with-missing-data.tsx"
import "./ModalRuntime-coverage.test.parsemodalyaml.tsx"
import "./ModalRuntime-coverage.test.modalruntime-without-tabs.tsx"
import "./ModalRuntime-coverage.test.modalruntime-custom-section-with-no-content.tsx"
