/**
 * Supplemental tests for hooks/mcp/dedup.ts
 *
 * Covers three behaviors not exercised in dedup.test.ts or dedup-coverage.test.ts:
 *   1. Zero-value cpuRequestsCores / memoryRequestsGB preserved via != null (#11727)
 *   2. pvcCount / pvcBoundCount travel with the bestMetrics capacity snapshot
 *   3. A three-cluster group collapses to one result with exactly two aliases
 */

import { describe, it, expect } from 'vitest'
import type { ClusterInfo } from '../types'
import { deduplicateClustersByServer } from '../dedup'

function makeCluster(overrides: Partial<ClusterInfo> = {}): ClusterInfo {
  return {
    name: 'test-cluster',
    context: 'test-context',
    ...overrides,
  }
}

// ---------------------------------------------------------------------------
// Test data constants
// ---------------------------------------------------------------------------

const SHARED_SERVER = 'https://api.example.com'
const PRIMARY_CPU_CORES = 16
const ZERO_CPU_REQUEST_CORES = 0
const ZERO_CPU_REQUEST_MILLICORES = 0
const ZERO_MEMORY_REQUEST_GB = 0
const ZERO_MEMORY_REQUEST_BYTES = 0
const PVC_COUNT = 7
const PVC_BOUND_COUNT = 5
// Auto-generated names detected by the :6443/ and :443/ patterns in
// isAutoGeneratedName() (dedup.ts). Using these ensures the primary cluster
// wins the sort and the aliases are correctly relegated.
const AUTO_NAME_6443 = 'ctx/api-server:6443/admin'
const AUTO_NAME_443 = 'ctx/api-server:443/admin'

// ---------------------------------------------------------------------------
// Gap 1 — zero-value request metric preservation (issue #11727)
//
// The legacy merge loop at dedup.ts:219-228 uses `!= null` (not `=== undefined`)
// so that a literal 0 is treated as a real measurement, not as "absent". Before
// that fix a cluster reporting 0 CPU/memory requests was silently skipped, making
// the metric appear as though it was never recorded.
// ---------------------------------------------------------------------------

describe('deduplicateClustersByServer — zero-value request metric preservation (#11727)', () => {
  it('preserves cpuRequestsCores: 0 from alias when primary has no request metrics', () => {
    const primary = makeCluster({
      name: 'primary',
      server: SHARED_SERVER,
      cpuCores: PRIMARY_CPU_CORES,
      // cpuRequestsCores intentionally absent — bestMetrics starts with undefined here
    })
    const alias = makeCluster({
      name: AUTO_NAME_6443,
      server: SHARED_SERVER,
      cpuRequestsCores: ZERO_CPU_REQUEST_CORES,
      cpuRequestsMillicores: ZERO_CPU_REQUEST_MILLICORES,
    })

    const result = deduplicateClustersByServer([primary, alias])

    expect(result).toHaveLength(1)
    expect(result[0].cpuRequestsCores).toBe(ZERO_CPU_REQUEST_CORES)
    expect(result[0].cpuRequestsMillicores).toBe(ZERO_CPU_REQUEST_MILLICORES)
  })

  it('preserves memoryRequestsGB: 0 from alias when primary has no request metrics', () => {
    const primary = makeCluster({
      name: 'primary',
      server: SHARED_SERVER,
      cpuCores: PRIMARY_CPU_CORES,
      // memoryRequestsGB intentionally absent
    })
    const alias = makeCluster({
      name: AUTO_NAME_6443,
      server: SHARED_SERVER,
      memoryRequestsGB: ZERO_MEMORY_REQUEST_GB,
      memoryRequestsBytes: ZERO_MEMORY_REQUEST_BYTES,
    })

    const result = deduplicateClustersByServer([primary, alias])

    expect(result).toHaveLength(1)
    expect(result[0].memoryRequestsGB).toBe(ZERO_MEMORY_REQUEST_GB)
    expect(result[0].memoryRequestsBytes).toBe(ZERO_MEMORY_REQUEST_BYTES)
  })
})

// ---------------------------------------------------------------------------
// Gap 2 — pvcCount / pvcBoundCount in the bestMetrics capacity snapshot
//
// Both fields are collected at dedup.ts:198-200 into the bestMetrics object
// from whichever cluster first supplies a truthy cpuCores value. There is no
// separate merge loop for PVC fields — they must be included in the initial
// snapshot or they are lost.
// ---------------------------------------------------------------------------

describe('deduplicateClustersByServer — pvcCount / pvcBoundCount in bestMetrics', () => {
  it('includes pvcCount and pvcBoundCount from the capacity-bearing cluster in the result', () => {
    const primary = makeCluster({
      name: 'primary',
      server: SHARED_SERVER,
      // cpuCores, pvcCount and pvcBoundCount intentionally absent so the only
      // path for these fields to reach the output is via bestMetrics (dedup.ts:198-200).
    })
    const alias = makeCluster({
      name: AUTO_NAME_6443,
      server: SHARED_SERVER,
      cpuCores: PRIMARY_CPU_CORES,
      pvcCount: PVC_COUNT,
      pvcBoundCount: PVC_BOUND_COUNT,
    })

    const result = deduplicateClustersByServer([primary, alias])

    expect(result).toHaveLength(1)
    expect(result[0].pvcCount).toBe(PVC_COUNT)
    expect(result[0].pvcBoundCount).toBe(PVC_BOUND_COUNT)
  })
})

// ---------------------------------------------------------------------------
// Gap 3 — three-cluster group produces exactly two aliases
//
// dedup.ts:171: `sorted.slice(1).map(c => c.name)` — every cluster after the
// primary becomes an alias. Existing tests only exercise pairs; this is the
// first test that verifies the slice boundary with a group of three, ensuring
// both non-primary names appear in aliases[] and the primary is absent.
// ---------------------------------------------------------------------------

describe('deduplicateClustersByServer — three-cluster group produces two aliases', () => {
  it('collapses three same-server clusters into one result with exactly two aliases', () => {
    const primary = makeCluster({
      name: 'prow',
      server: SHARED_SERVER,
      cpuCores: PRIMARY_CPU_CORES,
    })
    const alias1 = makeCluster({
      name: AUTO_NAME_6443,
      server: SHARED_SERVER,
    })
    const alias2 = makeCluster({
      name: AUTO_NAME_443,
      server: SHARED_SERVER,
    })

    const result = deduplicateClustersByServer([primary, alias1, alias2])

    expect(result).toHaveLength(1)
    expect(result[0].name).toBe('prow')
    expect(result[0].aliases).toHaveLength(2)
    expect(result[0].aliases).toContain(AUTO_NAME_6443)
    expect(result[0].aliases).toContain(AUTO_NAME_443)
    expect(result[0].aliases).not.toContain('prow')
  })
})
