/* Split from shared-websocket-detect.test.ts for focused test modules. */
import "./shared-websocket-detect.test.connectsharedwebsocket.ts"
import "./shared-websocket-detect.test.updatesingleclusterincache-distribution-update.ts"
import "./shared-websocket-detect.test.fullfetchclusters-agent-success-path.ts"
import "./shared-websocket-detect.test.refreshsinglecluster-transient-failure-preserves-data.ts"
import "./shared-websocket-detect.test.fetchsingleclusterhealth-backend-error-paths.ts"
import "./shared-websocket-detect.test.mergewithstoredclusters-edge-cases-via-updateclustercache.ts"
import "./shared-websocket-detect.test.updatesingleclusterincache-memoryusagegb-and-metricsavailable-sharing.ts"
import "./shared-websocket-detect.test.updatesingleclusterincache-multiple-metrics-keys-protection.ts"
import "./shared-websocket-detect.test.deduplicateclustersbyserver-pvccount-and-pvcboundcount-merge.ts"
import "./shared-websocket-detect.test.sharemetricsbetweensameserverclusters-metricsavailable-sharing.ts"
import "./shared-websocket-detect.test.loadclustercachefromstorage-filtering-via-module-init-and-updateclustercache.ts"
import "./shared-websocket-detect.test.gke-detection-from-gke-io-url.ts"
import "./shared-websocket-detect.test.aks-detection-from-hcp-url.ts"
import "./shared-websocket-detect.test.oci-detection-from-oci-url.ts"
import "./shared-websocket-detect.test.openshift-detection-from-generic-api-pattern-with-6443.ts"
