/* Split from workloads-coverage.test.ts for focused test modules. */
import "./workloads-coverage.test.usepods-localstorage-cache-edges.ts"
import "./workloads-coverage.test.usepods-sse-progressive-updates.ts"
import "./workloads-coverage.test.usepods-error-edge-cases.ts"
import "./workloads-coverage.test.usepods-silent-refresh-behavior.ts"
import "./workloads-coverage.test.useallpods-error-branches.ts"
import "./workloads-coverage.test.usepodissues-uncovered-branches.ts"
import "./workloads-coverage.test.usedeploymentissues-uncovered-branches.ts"
import "./workloads-coverage.test.usedeployments-uncovered-branches.ts"
import "./workloads-coverage.test.usejobs-uncovered-branches.ts"
import "./workloads-coverage.test.usehpas-uncovered-branches.ts"
import "./workloads-coverage.test.usereplicasets-uncovered-branches.ts"
import "./workloads-coverage.test.usestatefulsets-uncovered-branches.ts"
import "./workloads-coverage.test.usedaemonsets-uncovered-branches.ts"
import "./workloads-coverage.test.usecronjobs-uncovered-branches.ts"
import "./workloads-coverage.test.usepodlogs-uncovered-branches.ts"
import "./workloads-coverage.test.subscribeworkloadscache-notification.ts"
