name: Add Help Wanted Label

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  label:
    uses: kubestellar/infra/.github/workflows/reusable-add-help-wanted.yml@88f4d5fff50ceea648cdd3848ed1835ebded5fe3 # main
    secrets: inherit
