name: Assignment Helper

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assignment-helper:
    uses: kubestellar/infra/.github/workflows/reusable-assignment-helper.yml@88f4d5fff50ceea648cdd3848ed1835ebded5fe3 # main
