name: "PR Title Verifier"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  verify:
    uses: kubestellar/infra/.github/workflows/reusable-pr-verify-title.yml@88f4d5fff50ceea648cdd3848ed1835ebded5fe3 # main
    secrets: inherit
