name: PR Verifier

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  checks: write
  pull-requests: read

jobs:
  verify:
    uses: kubestellar/infra/.github/workflows/reusable-pr-verifier.yml@5c7fdcdde035388fa2df43d860d2372c2dd3e3ed # pin to infra main
    secrets: inherit
